//! Static description of the magnetics data dictionary, used to build and resolve paths.
//!
//! **WARNING** This file is autogenerated by `rust/imas_rs/imas_updater/build_ids.py`.
//! Any changes will be overwritten.
//!
//! Each leaf carries the function that reads it out of the IDS, so the path a
//! reader follows is written once and checked by the compiler. The `read` closures
//! capture nothing, so they coerce to plain `fn` pointers and the whole description
//! stays a `static`.

#![allow(clippy::all)]

use super::{IndexSpec, Leaf, Node, NodeKind, gather, no_levels};
use crate::dd_base_types::{FLT_0D, FLT_1D, INT_0D, INT_1D, INT_2D, STR_0D};
use crate::ids::magnetics::Magnetics;
use std::any::Any;

// ============================================================================
// Array-of-structures lengths
// ============================================================================

/// Length of each array-of-structures level along `b_field_phi_probe`.
fn lengths_b_field_phi_probe(magnetics: &Magnetics, level: usize, _at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.b_field_phi_probe.len()),
        _ => return None,
    }
}

/// Length of each array-of-structures level along `b_field_pol_probe`.
fn lengths_b_field_pol_probe(magnetics: &Magnetics, level: usize, _at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.b_field_pol_probe.len()),
        _ => return None,
    }
}

/// Length of each array-of-structures level along `code_library`.
fn lengths_code_library(magnetics: &Magnetics, level: usize, _at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.code.library.len()),
        _ => return None,
    }
}

/// Length of each array-of-structures level along `diamagnetic_flux`.
fn lengths_diamagnetic_flux(magnetics: &Magnetics, level: usize, _at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.diamagnetic_flux.len()),
        _ => return None,
    }
}

/// Length of each array-of-structures level along `flux_loop`.
fn lengths_flux_loop(magnetics: &Magnetics, level: usize, _at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.flux_loop.len()),
        _ => return None,
    }
}

/// Length of each array-of-structures level along `flux_loop_position`.
fn lengths_flux_loop_position(magnetics: &Magnetics, level: usize, at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.flux_loop.len()),
        1 => return Some(magnetics.flux_loop[at[0]].position.len()),
        _ => return None,
    }
}

/// Length of each array-of-structures level along `ip`.
fn lengths_ip(magnetics: &Magnetics, level: usize, _at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.ip.len()),
        _ => return None,
    }
}

/// Length of each array-of-structures level along `rogowski_coil`.
fn lengths_rogowski_coil(magnetics: &Magnetics, level: usize, _at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.rogowski_coil.len()),
        _ => return None,
    }
}

/// Length of each array-of-structures level along `rogowski_coil_position`.
fn lengths_rogowski_coil_position(magnetics: &Magnetics, level: usize, at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.rogowski_coil.len()),
        1 => return Some(magnetics.rogowski_coil[at[0]].position.len()),
        _ => return None,
    }
}

/// Length of each array-of-structures level along `shunt`.
fn lengths_shunt(magnetics: &Magnetics, level: usize, _at: &[usize]) -> Option<usize> {
    match level {
        0 => return Some(magnetics.shunt.len()),
        _ => return None,
    }
}

// ============================================================================
// Nodes
// ============================================================================

static NODES_FLUX_LOOP_TYPE: &[Node] = &[
    Node {
        name: "name",
        documentation: "Short string identifier",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.flux_loop[at[0]].r#type.name.clone()
                })
            },
        }),
    },
    Node {
        name: "index",
        documentation: "Integer identifier (enumeration index within a list). Private identifier values must be indicated by a negative index.",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> INT_0D {
                    magnetics.flux_loop[at[0]].r#type.index.clone()
                })
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Verbose description",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.flux_loop[at[0]].r#type.description.clone()
                })
            },
        }),
    },
];

static NODES_FLUX_LOOP_POSITION: &[Node] = &[
    Node {
        name: "r",
        documentation: "Major radius",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    2,
                    lengths_flux_loop_position,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.flux_loop[at[0]].position[at[1]].r.clone() },
                )
            },
        }),
    },
    Node {
        name: "phi",
        documentation: "Toroidal angle (oriented counter-clockwise when viewed from above)",
        units: "rad",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    2,
                    lengths_flux_loop_position,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.flux_loop[at[0]].position[at[1]].phi.clone() },
                )
            },
        }),
    },
    Node {
        name: "z",
        documentation: "Height",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    2,
                    lengths_flux_loop_position,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.flux_loop[at[0]].position[at[1]].z.clone() },
                )
            },
        }),
    },
];

static NODES_FLUX_LOOP_FLUX: &[Node] = &[
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.flux_loop[at[0]].flux.data.clone()
                })
            },
        }),
    },
    Node {
        name: "validity_timed",
        documentation: "Indicator of the validity of the data for each time slice. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> INT_1D {
                    magnetics.flux_loop[at[0]].flux.validity_timed.clone()
                })
            },
        }),
    },
    Node {
        name: "validity",
        documentation: "Indicator of the validity of the data for the whole acquisition period. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> INT_0D {
                    magnetics.flux_loop[at[0]].flux.validity.clone()
                })
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.flux_loop[at[0]].flux.time.clone()
                })
            },
        }),
    },
];

static NODES_FLUX_LOOP_VOLTAGE: &[Node] = &[
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.flux_loop[at[0]].voltage.data.clone()
                })
            },
        }),
    },
    Node {
        name: "validity_timed",
        documentation: "Indicator of the validity of the data for each time slice. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> INT_1D {
                    magnetics.flux_loop[at[0]].voltage.validity_timed.clone()
                })
            },
        }),
    },
    Node {
        name: "validity",
        documentation: "Indicator of the validity of the data for the whole acquisition period. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> INT_0D {
                    magnetics.flux_loop[at[0]].voltage.validity.clone()
                })
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.flux_loop[at[0]].voltage.time.clone()
                })
            },
        }),
    },
];

static NODES_FLUX_LOOP: &[Node] = &[
    Node {
        name: "name",
        documentation: "Short string identifier (unique for a given device)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.flux_loop[at[0]].name.clone()
                })
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Description, e.g. “channel viewing the upper divertor”",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.flux_loop[at[0]].description.clone()
                })
            },
        }),
    },
    Node {
        name: "type",
        documentation: "Flux loop type",
        units: "",
        kind: NodeKind::Structure(NODES_FLUX_LOOP_TYPE),
    },
    Node {
        name: "position",
        documentation: "List of (R,phi,Z) points defining the outline of the flux loop. Leave empty if ../type/index = 6 (differential loop)",
        units: "",
        kind: NodeKind::ArrayOfStructures(NODES_FLUX_LOOP_POSITION),
    },
    Node {
        name: "indices_differential",
        documentation: "Indices (from the flux_loop array of structures) of the two loops used to build a differential measurement: loop(second index) - loop(first index). Use only if ../type/index = 6, leave empty otherwise.",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> INT_1D {
                    magnetics.flux_loop[at[0]].indices_differential.clone()
                })
            },
        }),
    },
    Node {
        name: "area",
        documentation: "Effective area (ratio between flux and average magnetic field over the loop). Leave empty if ../type/index = 6 (differential loop)",
        units: "m^2",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> FLT_0D {
                    magnetics.flux_loop[at[0]].area.clone()
                })
            },
        }),
    },
    Node {
        name: "gm9",
        documentation: "Integral of 1/R over the loop area (ratio between flux and magnetic rigidity R0.B0). Use only if ../type/index = 3 to 5, leave empty otherwise.",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_flux_loop, |magnetics: &Magnetics, at: &[usize]| -> FLT_0D {
                    magnetics.flux_loop[at[0]].gm9.clone()
                })
            },
        }),
    },
    Node {
        name: "flux",
        documentation: "Measured magnetic flux through loop with normal to enclosed surface determined by order of points",
        units: "Wb",
        kind: NodeKind::Structure(NODES_FLUX_LOOP_FLUX),
    },
    Node {
        name: "voltage",
        documentation: "Measured voltage between the loop terminals",
        units: "V",
        kind: NodeKind::Structure(NODES_FLUX_LOOP_VOLTAGE),
    },
];

static NODES_B_FIELD_POL_PROBE_TYPE: &[Node] = &[
    Node {
        name: "name",
        documentation: "Short string identifier",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> STR_0D { magnetics.b_field_pol_probe[at[0]].r#type.name.clone() },
                )
            },
        }),
    },
    Node {
        name: "index",
        documentation: "Integer identifier (enumeration index within a list). Private identifier values must be indicated by a negative index.",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_0D { magnetics.b_field_pol_probe[at[0]].r#type.index.clone() },
                )
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Verbose description",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> STR_0D { magnetics.b_field_pol_probe[at[0]].r#type.description.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_POL_PROBE_POSITION: &[Node] = &[
    Node {
        name: "r",
        documentation: "Major radius",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_pol_probe[at[0]].position.r.clone() },
                )
            },
        }),
    },
    Node {
        name: "phi",
        documentation: "Toroidal angle (oriented counter-clockwise when viewed from above)",
        units: "rad",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_pol_probe[at[0]].position.phi.clone() },
                )
            },
        }),
    },
    Node {
        name: "z",
        documentation: "Height",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_pol_probe[at[0]].position.z.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_POL_PROBE_FIELD: &[Node] = &[
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_pol_probe[at[0]].field.data.clone() },
                )
            },
        }),
    },
    Node {
        name: "validity_timed",
        documentation: "Indicator of the validity of the data for each time slice. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_1D { magnetics.b_field_pol_probe[at[0]].field.validity_timed.clone() },
                )
            },
        }),
    },
    Node {
        name: "validity",
        documentation: "Indicator of the validity of the data for the whole acquisition period. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_0D { magnetics.b_field_pol_probe[at[0]].field.validity.clone() },
                )
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_pol_probe[at[0]].field.time.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_POL_PROBE_VOLTAGE: &[Node] = &[
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_pol_probe[at[0]].voltage.data.clone() },
                )
            },
        }),
    },
    Node {
        name: "validity_timed",
        documentation: "Indicator of the validity of the data for each time slice. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_1D { magnetics.b_field_pol_probe[at[0]].voltage.validity_timed.clone() },
                )
            },
        }),
    },
    Node {
        name: "validity",
        documentation: "Indicator of the validity of the data for the whole acquisition period. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_0D { magnetics.b_field_pol_probe[at[0]].voltage.validity.clone() },
                )
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_pol_probe[at[0]].voltage.time.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_POL_PROBE_NON_LINEAR_RESPONSE: &[Node] = &[
    Node {
        name: "b_field_linear",
        documentation: "Array of magnetic field values (corresponding to the assumption of a linear relation between magnetic field and probe coil current), for each of which the probe non-linear response is given in ../b_field_non_linear",
        units: "T",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_pol_probe[at[0]].non_linear_response.b_field_linear.clone() },
                )
            },
        }),
    },
    Node {
        name: "b_field_non_linear",
        documentation: "Magnetic field value taking into account the non-linear response of the probe",
        units: "T",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_pol_probe[at[0]].non_linear_response.b_field_non_linear.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_POL_PROBE: &[Node] = &[
    Node {
        name: "name",
        documentation: "Short string identifier (unique for a given device)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> STR_0D { magnetics.b_field_pol_probe[at[0]].name.clone() },
                )
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Description, e.g. “channel viewing the upper divertor”",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> STR_0D { magnetics.b_field_pol_probe[at[0]].description.clone() },
                )
            },
        }),
    },
    Node {
        name: "type",
        documentation: "Probe type",
        units: "",
        kind: NodeKind::Structure(NODES_B_FIELD_POL_PROBE_TYPE),
    },
    Node {
        name: "position",
        documentation: "R, Z, Phi position of the coil centre",
        units: "",
        kind: NodeKind::Structure(NODES_B_FIELD_POL_PROBE_POSITION),
    },
    Node {
        name: "poloidal_angle",
        documentation: "Angle of the sensor normal vector (vector parallel to the the axis of the coil, n on the diagram) with respect to horizontal plane (clockwise theta-like angle). Zero if sensor normal vector fully in the horizontal plane and oriented towards increasing major radius. Values in [0 , 2Pi]",
        units: "rad",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_pol_probe[at[0]].poloidal_angle.clone() },
                )
            },
        }),
    },
    Node {
        name: "toroidal_angle",
        documentation: "Angle of the projection of the sensor normal vector (n) in the horizontal plane with the increasing R direction (i.e. grad(R)) (angle is counter-clockwise from above). Values should be taken modulo pi with values within (-pi/2,pi/2]. Zero if projected sensor normal is parallel to grad(R), pi/2 if it is parallel to grad(phi).",
        units: "rad",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_pol_probe[at[0]].toroidal_angle.clone() },
                )
            },
        }),
    },
    Node {
        name: "indices_differential",
        documentation: "Indices (from the b_field_pol_probe array of structure) of the two probes used to build the field difference field(second index) - field(first index). Use only if ../type/index = 6, leave empty otherwise",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_1D { magnetics.b_field_pol_probe[at[0]].indices_differential.clone() },
                )
            },
        }),
    },
    Node {
        name: "bandwidth_3db",
        documentation: "3dB bandwith (first index : lower frequency bound, second index : upper frequency bound)",
        units: "Hz",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_pol_probe[at[0]].bandwidth_3db.clone() },
                )
            },
        }),
    },
    Node {
        name: "area",
        documentation: "Area of each turn of the sensor; becomes effective area when multiplied by the turns",
        units: "m^2",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_pol_probe[at[0]].area.clone() },
                )
            },
        }),
    },
    Node {
        name: "length",
        documentation: "Length of the sensor along it's normal vector (n)",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_pol_probe[at[0]].length.clone() },
                )
            },
        }),
    },
    Node {
        name: "turns",
        documentation: "Turns in the coil, including sign",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_pol_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_0D { magnetics.b_field_pol_probe[at[0]].turns.clone() },
                )
            },
        }),
    },
    Node {
        name: "field",
        documentation: "Magnetic field component in direction of sensor normal axis (n) averaged over sensor volume defined by area and length, where n = cos(poloidal_angle)*cos(toroidal_angle)*grad(R) - sin(poloidal_angle)*grad(Z) + cos(poloidal_angle)*sin(toroidal_angle)*grad(Phi)/norm(grad(Phi))",
        units: "T",
        kind: NodeKind::Structure(NODES_B_FIELD_POL_PROBE_FIELD),
    },
    Node {
        name: "voltage",
        documentation: "Voltage on the coil terminals",
        units: "V",
        kind: NodeKind::Structure(NODES_B_FIELD_POL_PROBE_VOLTAGE),
    },
    Node {
        name: "non_linear_response",
        documentation: "Non-linear response of the probe (typically in case of a Hall probe)",
        units: "",
        kind: NodeKind::Structure(NODES_B_FIELD_POL_PROBE_NON_LINEAR_RESPONSE),
    },
];

static NODES_B_FIELD_PHI_PROBE_TYPE: &[Node] = &[
    Node {
        name: "name",
        documentation: "Short string identifier",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> STR_0D { magnetics.b_field_phi_probe[at[0]].r#type.name.clone() },
                )
            },
        }),
    },
    Node {
        name: "index",
        documentation: "Integer identifier (enumeration index within a list). Private identifier values must be indicated by a negative index.",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_0D { magnetics.b_field_phi_probe[at[0]].r#type.index.clone() },
                )
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Verbose description",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> STR_0D { magnetics.b_field_phi_probe[at[0]].r#type.description.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_PHI_PROBE_POSITION: &[Node] = &[
    Node {
        name: "r",
        documentation: "Major radius",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_phi_probe[at[0]].position.r.clone() },
                )
            },
        }),
    },
    Node {
        name: "phi",
        documentation: "Toroidal angle (oriented counter-clockwise when viewed from above)",
        units: "rad",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_phi_probe[at[0]].position.phi.clone() },
                )
            },
        }),
    },
    Node {
        name: "z",
        documentation: "Height",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_phi_probe[at[0]].position.z.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_PHI_PROBE_FIELD: &[Node] = &[
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_phi_probe[at[0]].field.data.clone() },
                )
            },
        }),
    },
    Node {
        name: "validity_timed",
        documentation: "Indicator of the validity of the data for each time slice. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_1D { magnetics.b_field_phi_probe[at[0]].field.validity_timed.clone() },
                )
            },
        }),
    },
    Node {
        name: "validity",
        documentation: "Indicator of the validity of the data for the whole acquisition period. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_0D { magnetics.b_field_phi_probe[at[0]].field.validity.clone() },
                )
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_phi_probe[at[0]].field.time.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_PHI_PROBE_VOLTAGE: &[Node] = &[
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_phi_probe[at[0]].voltage.data.clone() },
                )
            },
        }),
    },
    Node {
        name: "validity_timed",
        documentation: "Indicator of the validity of the data for each time slice. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_1D { magnetics.b_field_phi_probe[at[0]].voltage.validity_timed.clone() },
                )
            },
        }),
    },
    Node {
        name: "validity",
        documentation: "Indicator of the validity of the data for the whole acquisition period. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_0D { magnetics.b_field_phi_probe[at[0]].voltage.validity.clone() },
                )
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_phi_probe[at[0]].voltage.time.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_PHI_PROBE_NON_LINEAR_RESPONSE: &[Node] = &[
    Node {
        name: "b_field_linear",
        documentation: "Array of magnetic field values (corresponding to the assumption of a linear relation between magnetic field and probe coil current), for each of which the probe non-linear response is given in ../b_field_non_linear",
        units: "T",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_phi_probe[at[0]].non_linear_response.b_field_linear.clone() },
                )
            },
        }),
    },
    Node {
        name: "b_field_non_linear",
        documentation: "Magnetic field value taking into account the non-linear response of the probe",
        units: "T",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_phi_probe[at[0]].non_linear_response.b_field_non_linear.clone() },
                )
            },
        }),
    },
];

static NODES_B_FIELD_PHI_PROBE: &[Node] = &[
    Node {
        name: "name",
        documentation: "Short string identifier (unique for a given device)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> STR_0D { magnetics.b_field_phi_probe[at[0]].name.clone() },
                )
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Description, e.g. “channel viewing the upper divertor”",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> STR_0D { magnetics.b_field_phi_probe[at[0]].description.clone() },
                )
            },
        }),
    },
    Node {
        name: "type",
        documentation: "Probe type",
        units: "",
        kind: NodeKind::Structure(NODES_B_FIELD_PHI_PROBE_TYPE),
    },
    Node {
        name: "position",
        documentation: "R, Z, Phi position of the coil centre",
        units: "",
        kind: NodeKind::Structure(NODES_B_FIELD_PHI_PROBE_POSITION),
    },
    Node {
        name: "poloidal_angle",
        documentation: "Angle of the sensor normal vector (vector parallel to the the axis of the coil, n on the diagram) with respect to horizontal plane (clockwise theta-like angle). Zero if sensor normal vector fully in the horizontal plane and oriented towards increasing major radius. Values in [0 , 2Pi]",
        units: "rad",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_phi_probe[at[0]].poloidal_angle.clone() },
                )
            },
        }),
    },
    Node {
        name: "toroidal_angle",
        documentation: "Angle of the projection of the sensor normal vector (n) in the horizontal plane with the increasing R direction (i.e. grad(R)) (angle is counter-clockwise from above). Values should be taken modulo pi with values within (-pi/2,pi/2]. Zero if projected sensor normal is parallel to grad(R), pi/2 if it is parallel to grad(phi).",
        units: "rad",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_phi_probe[at[0]].toroidal_angle.clone() },
                )
            },
        }),
    },
    Node {
        name: "indices_differential",
        documentation: "Indices (from the b_field_pol_probe array of structure) of the two probes used to build the field difference field(second index) - field(first index). Use only if ../type/index = 6, leave empty otherwise",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_1D { magnetics.b_field_phi_probe[at[0]].indices_differential.clone() },
                )
            },
        }),
    },
    Node {
        name: "bandwidth_3db",
        documentation: "3dB bandwith (first index : lower frequency bound, second index : upper frequency bound)",
        units: "Hz",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.b_field_phi_probe[at[0]].bandwidth_3db.clone() },
                )
            },
        }),
    },
    Node {
        name: "area",
        documentation: "Area of each turn of the sensor; becomes effective area when multiplied by the turns",
        units: "m^2",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_phi_probe[at[0]].area.clone() },
                )
            },
        }),
    },
    Node {
        name: "length",
        documentation: "Length of the sensor along it's normal vector (n)",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.b_field_phi_probe[at[0]].length.clone() },
                )
            },
        }),
    },
    Node {
        name: "turns",
        documentation: "Turns in the coil, including sign",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_b_field_phi_probe,
                    |magnetics: &Magnetics, at: &[usize]| -> INT_0D { magnetics.b_field_phi_probe[at[0]].turns.clone() },
                )
            },
        }),
    },
    Node {
        name: "field",
        documentation: "Magnetic field component in direction of sensor normal axis (n) averaged over sensor volume defined by area and length, where n = cos(poloidal_angle)*cos(toroidal_angle)*grad(R) - sin(poloidal_angle)*grad(Z) + cos(poloidal_angle)*sin(toroidal_angle)*grad(Phi)/norm(grad(Phi))",
        units: "T",
        kind: NodeKind::Structure(NODES_B_FIELD_PHI_PROBE_FIELD),
    },
    Node {
        name: "voltage",
        documentation: "Voltage on the coil terminals",
        units: "V",
        kind: NodeKind::Structure(NODES_B_FIELD_PHI_PROBE_VOLTAGE),
    },
    Node {
        name: "non_linear_response",
        documentation: "Non-linear response of the probe (typically in case of a Hall probe)",
        units: "",
        kind: NodeKind::Structure(NODES_B_FIELD_PHI_PROBE_NON_LINEAR_RESPONSE),
    },
];

static NODES_ROGOWSKI_COIL_MEASURED_QUANTITY: &[Node] = &[
    Node {
        name: "name",
        documentation: "Short string identifier",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.rogowski_coil[at[0]].measured_quantity.name.clone()
                })
            },
        }),
    },
    Node {
        name: "index",
        documentation: "Integer identifier (enumeration index within a list). Private identifier values must be indicated by a negative index.",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> INT_0D {
                    magnetics.rogowski_coil[at[0]].measured_quantity.index.clone()
                })
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Verbose description",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.rogowski_coil[at[0]].measured_quantity.description.clone()
                })
            },
        }),
    },
];

static NODES_ROGOWSKI_COIL_POSITION: &[Node] = &[
    Node {
        name: "r",
        documentation: "Major radius",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    2,
                    lengths_rogowski_coil_position,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.rogowski_coil[at[0]].position[at[1]].r.clone() },
                )
            },
        }),
    },
    Node {
        name: "phi",
        documentation: "Toroidal angle (oriented counter-clockwise when viewed from above)",
        units: "rad",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    2,
                    lengths_rogowski_coil_position,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.rogowski_coil[at[0]].position[at[1]].phi.clone() },
                )
            },
        }),
    },
    Node {
        name: "z",
        documentation: "Height",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    2,
                    lengths_rogowski_coil_position,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_0D { magnetics.rogowski_coil[at[0]].position[at[1]].z.clone() },
                )
            },
        }),
    },
];

static NODES_ROGOWSKI_COIL_CURRENT: &[Node] = &[
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.rogowski_coil[at[0]].current.data.clone()
                })
            },
        }),
    },
    Node {
        name: "validity_timed",
        documentation: "Indicator of the validity of the data for each time slice. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> INT_1D {
                    magnetics.rogowski_coil[at[0]].current.validity_timed.clone()
                })
            },
        }),
    },
    Node {
        name: "validity",
        documentation: "Indicator of the validity of the data for the whole acquisition period. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> INT_0D {
                    magnetics.rogowski_coil[at[0]].current.validity.clone()
                })
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.rogowski_coil[at[0]].current.time.clone()
                })
            },
        }),
    },
];

static NODES_ROGOWSKI_COIL: &[Node] = &[
    Node {
        name: "name",
        documentation: "Short string identifier (unique for a given device)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.rogowski_coil[at[0]].name.clone()
                })
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Description, e.g. “channel viewing the upper divertor”",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.rogowski_coil[at[0]].description.clone()
                })
            },
        }),
    },
    Node {
        name: "measured_quantity",
        documentation: "Quantity measured by the sensor",
        units: "",
        kind: NodeKind::Structure(NODES_ROGOWSKI_COIL_MEASURED_QUANTITY),
    },
    Node {
        name: "position",
        documentation: "List of (R,Z,phi) points defining the position of the coil guiding centre. Values defining a single segment must be entered in contiguous order",
        units: "",
        kind: NodeKind::ArrayOfStructures(NODES_ROGOWSKI_COIL_POSITION),
    },
    Node {
        name: "indices_compound",
        documentation: "Indices (from the rogowski_coil array of structure) of the partial Rogowskis used to build the coumpound signal (sum of the partial Rogowski signals). Can be set to any unique integer value for each section of a compound Rogowski coil. Use only if ../measure_quantity/index = 5, leave empty otherwise",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> INT_1D {
                    magnetics.rogowski_coil[at[0]].indices_compound.clone()
                })
            },
        }),
    },
    Node {
        name: "area",
        documentation: "Effective area of the loop wrapped around the guiding centre. In case of multiple layers, sum of the areas of each layer",
        units: "m^2",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> FLT_0D {
                    magnetics.rogowski_coil[at[0]].area.clone()
                })
            },
        }),
    },
    Node {
        name: "turns_per_metre",
        documentation: "Number of turns per unit length. In case of multiple layers, turns are counted for a single layer",
        units: "m^-1",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_rogowski_coil, |magnetics: &Magnetics, at: &[usize]| -> FLT_0D {
                    magnetics.rogowski_coil[at[0]].turns_per_metre.clone()
                })
            },
        }),
    },
    Node {
        name: "current",
        documentation: "Measured current inside the Rogowski coil contour. The normal direction to the Rogowski coil is defined by the order of points in the list of guiding centre positions. The current is positive when oriented in the same direction as the normal.",
        units: "A",
        kind: NodeKind::Structure(NODES_ROGOWSKI_COIL_CURRENT),
    },
];

static NODES_SHUNT_POSITION_FIRST_POINT: &[Node] = &[
    Node {
        name: "r",
        documentation: "Major radius",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> FLT_0D {
                    magnetics.shunt[at[0]].position.first_point.r.clone()
                })
            },
        }),
    },
    Node {
        name: "z",
        documentation: "Height",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> FLT_0D {
                    magnetics.shunt[at[0]].position.first_point.z.clone()
                })
            },
        }),
    },
];

static NODES_SHUNT_POSITION_SECOND_POINT: &[Node] = &[
    Node {
        name: "r",
        documentation: "Major radius",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> FLT_0D {
                    magnetics.shunt[at[0]].position.second_point.r.clone()
                })
            },
        }),
    },
    Node {
        name: "z",
        documentation: "Height",
        units: "m",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> FLT_0D {
                    magnetics.shunt[at[0]].position.second_point.z.clone()
                })
            },
        }),
    },
];

static NODES_SHUNT_POSITION: &[Node] = &[
    Node {
        name: "first_point",
        documentation: "Position of the first point",
        units: "",
        kind: NodeKind::Structure(NODES_SHUNT_POSITION_FIRST_POINT),
    },
    Node {
        name: "second_point",
        documentation: "Position of the second point",
        units: "",
        kind: NodeKind::Structure(NODES_SHUNT_POSITION_SECOND_POINT),
    },
];

static NODES_SHUNT_VOLTAGE: &[Node] = &[
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.shunt[at[0]].voltage.data.clone()
                })
            },
        }),
    },
    Node {
        name: "validity_timed",
        documentation: "Indicator of the validity of the data for each time slice. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> INT_1D {
                    magnetics.shunt[at[0]].voltage.validity_timed.clone()
                })
            },
        }),
    },
    Node {
        name: "validity",
        documentation: "Indicator of the validity of the data for the whole acquisition period. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> INT_0D {
                    magnetics.shunt[at[0]].voltage.validity.clone()
                })
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.shunt[at[0]].voltage.time.clone()
                })
            },
        }),
    },
];

static NODES_SHUNT: &[Node] = &[
    Node {
        name: "name",
        documentation: "Short string identifier (unique for a given device)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.shunt[at[0]].name.clone()
                })
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Description, e.g. “channel viewing the upper divertor”",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.shunt[at[0]].description.clone()
                })
            },
        }),
    },
    Node {
        name: "position",
        documentation: "Position of shunt terminals",
        units: "",
        kind: NodeKind::Structure(NODES_SHUNT_POSITION),
    },
    Node {
        name: "resistance",
        documentation: "Shunt resistance",
        units: "ohm",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> FLT_0D {
                    magnetics.shunt[at[0]].resistance.clone()
                })
            },
        }),
    },
    Node {
        name: "voltage",
        documentation: "Voltage on the shunt terminals (Vfirst_point-Vsecond_point)",
        units: "V",
        kind: NodeKind::Structure(NODES_SHUNT_VOLTAGE),
    },
    Node {
        name: "divertor_index",
        documentation: "If the shunt is located on a given divertor, index of that divertor in the divertors IDS",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> INT_0D {
                    magnetics.shunt[at[0]].divertor_index.clone()
                })
            },
        }),
    },
    Node {
        name: "target_index",
        documentation: "If the shunt is located on a divertor target, index of that target in the divertors IDS",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> INT_0D {
                    magnetics.shunt[at[0]].target_index.clone()
                })
            },
        }),
    },
    Node {
        name: "tile_index",
        documentation: "If the shunt is located on a divertor tile, index of that tile in the divertors IDS",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_shunt, |magnetics: &Magnetics, at: &[usize]| -> INT_0D {
                    magnetics.shunt[at[0]].tile_index.clone()
                })
            },
        }),
    },
];

static NODES_IP: &[Node] = &[
    Node {
        name: "method_name",
        documentation: "Name of the calculation method",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_ip, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.ip[at[0]].method_name.clone()
                })
            },
        }),
    },
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_ip, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.ip[at[0]].data.clone()
                })
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_ip, |magnetics: &Magnetics, at: &[usize]| -> FLT_1D {
                    magnetics.ip[at[0]].time.clone()
                })
            },
        }),
    },
];

static NODES_DIAMAGNETIC_FLUX: &[Node] = &[
    Node {
        name: "method_name",
        documentation: "Name of the calculation method",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_diamagnetic_flux,
                    |magnetics: &Magnetics, at: &[usize]| -> STR_0D { magnetics.diamagnetic_flux[at[0]].method_name.clone() },
                )
            },
        }),
    },
    Node {
        name: "data",
        documentation: "Data",
        units: "as_parent",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_diamagnetic_flux,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.diamagnetic_flux[at[0]].data.clone() },
                )
            },
        }),
    },
    Node {
        name: "time",
        documentation: "Time",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(
                    magnetics,
                    indices,
                    1,
                    lengths_diamagnetic_flux,
                    |magnetics: &Magnetics, at: &[usize]| -> FLT_1D { magnetics.diamagnetic_flux[at[0]].time.clone() },
                )
            },
        }),
    },
];

static NODES_CODE_LIBRARY: &[Node] = &[
    Node {
        name: "name",
        documentation: "Name of software",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_code_library, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.code.library[at[0]].name.clone()
                })
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Short description of the software (type, purpose)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_code_library, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.code.library[at[0]].description.clone()
                })
            },
        }),
    },
    Node {
        name: "commit",
        documentation: "Unique commit reference of software",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_code_library, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.code.library[at[0]].commit.clone()
                })
            },
        }),
    },
    Node {
        name: "version",
        documentation: "Unique version (tag) of software",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_code_library, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.code.library[at[0]].version.clone()
                })
            },
        }),
    },
    Node {
        name: "repository",
        documentation: "URL of software repository",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_code_library, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.code.library[at[0]].repository.clone()
                })
            },
        }),
    },
    Node {
        name: "parameters",
        documentation: "List of the code specific parameters in XML format",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 1, lengths_code_library, |magnetics: &Magnetics, at: &[usize]| -> STR_0D {
                    magnetics.code.library[at[0]].parameters.clone()
                })
            },
        }),
    },
];

static NODES_CODE: &[Node] = &[
    Node {
        name: "name",
        documentation: "Name of software generating IDS",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 0, no_levels, |magnetics: &Magnetics, _at: &[usize]| -> STR_0D {
                    magnetics.code.name.clone()
                })
            },
        }),
    },
    Node {
        name: "description",
        documentation: "Short description of the software (type, purpose)",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 0, no_levels, |magnetics: &Magnetics, _at: &[usize]| -> STR_0D {
                    magnetics.code.description.clone()
                })
            },
        }),
    },
    Node {
        name: "commit",
        documentation: "Unique commit reference of software",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 0, no_levels, |magnetics: &Magnetics, _at: &[usize]| -> STR_0D {
                    magnetics.code.commit.clone()
                })
            },
        }),
    },
    Node {
        name: "version",
        documentation: "Unique version (tag) of software",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 0, no_levels, |magnetics: &Magnetics, _at: &[usize]| -> STR_0D {
                    magnetics.code.version.clone()
                })
            },
        }),
    },
    Node {
        name: "repository",
        documentation: "URL of software repository",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 0, no_levels, |magnetics: &Magnetics, _at: &[usize]| -> STR_0D {
                    magnetics.code.repository.clone()
                })
            },
        }),
    },
    Node {
        name: "parameters",
        documentation: "List of the code specific parameters in XML format",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "STR_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 0, no_levels, |magnetics: &Magnetics, _at: &[usize]| -> STR_0D {
                    magnetics.code.parameters.clone()
                })
            },
        }),
    },
    Node {
        name: "output_flag",
        documentation: "Output flag : 0 means the run is successful, other values mean some difficulty has been encountered, the exact meaning is then code specific. Negative values mean the result shall not be used.",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_1D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 0, no_levels, |magnetics: &Magnetics, _at: &[usize]| -> INT_1D {
                    magnetics.code.output_flag.clone()
                })
            },
        }),
    },
    Node {
        name: "library",
        documentation: "List of external libraries used by the code that has produced this IDS",
        units: "",
        kind: NodeKind::ArrayOfStructures(NODES_CODE_LIBRARY),
    },
];

static NODES_ROOT: &[Node] = &[
    Node {
        name: "flux_loop",
        documentation: "Flux loops; partial flux loops can be described. In case of differential loops, the geometry of differential flux loops is stored in the flux_loop indices of the primitive loops. Signals may be stored on the primitive loop indices but this is optional if the index of the primitive loop is referenced by a differential loop index",
        units: "",
        kind: NodeKind::ArrayOfStructures(NODES_FLUX_LOOP),
    },
    Node {
        name: "b_field_pol_probe",
        documentation: "Poloidal field probes",
        units: "",
        kind: NodeKind::ArrayOfStructures(NODES_B_FIELD_POL_PROBE),
    },
    Node {
        name: "b_field_pol_probe_equivalent",
        documentation: "Indices of equivalent poloidal field probes (from the b_field_pol_probe array) that differ only by their toroidal position and have the same (R,Z) position and the same coil orientation (poloidal and toroidal angles). Sets of equivalent probes (i.e. sets of (R, Z, poloidal_angle and toroidal_angle) values) are grouped by the first coordinate and the coils belonging to a given set are listed along the second coordinate. As an example, if there are N probes in a poloidal cross section that are replicated at the same poloidal positions and with the same orientation at 8 toroidal positions, the matrix will be of size Nx8.",
        units: "",
        kind: NodeKind::Leaf(Leaf {
            data_type: "INT_2D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 0, no_levels, |magnetics: &Magnetics, _at: &[usize]| -> INT_2D {
                    magnetics.b_field_pol_probe_equivalent.clone()
                })
            },
        }),
    },
    Node {
        name: "b_field_phi_probe",
        documentation: "Toroidal field probes",
        units: "",
        kind: NodeKind::ArrayOfStructures(NODES_B_FIELD_PHI_PROBE),
    },
    Node {
        name: "rogowski_coil",
        documentation: "Set of Rogowski coils. If some of the coils form a compound Rogowski sensor, they must be entered in contiguous order",
        units: "",
        kind: NodeKind::ArrayOfStructures(NODES_ROGOWSKI_COIL),
    },
    Node {
        name: "shunt",
        documentation: "Set of shunt resistances through which currents in the divertor structure are measured. Shunts are modelled as piecewise straight line segments in the poloidal plane.",
        units: "",
        kind: NodeKind::ArrayOfStructures(NODES_SHUNT),
    },
    Node {
        name: "ip",
        documentation: "Plasma current. Positive sign means counter-clockwise when viewed from above. The array of structure corresponds to a set of calculation methods (starting with the generally recommended method).",
        units: "A",
        kind: NodeKind::ArrayOfStructures(NODES_IP),
    },
    Node {
        name: "diamagnetic_flux",
        documentation: "Diamagnetic flux. The array of structure corresponds to a set of calculation methods (starting with the generally recommended method). Positive sign means counter-clockwise when viewed from above",
        units: "Wb",
        kind: NodeKind::ArrayOfStructures(NODES_DIAMAGNETIC_FLUX),
    },
    Node {
        name: "latency",
        documentation: "Upper bound of the delay between physical information received by the detector and data available on the real-time (RT) network.",
        units: "s",
        kind: NodeKind::Leaf(Leaf {
            data_type: "FLT_0D",
            read: |ids: &dyn Any, indices: &[IndexSpec]| {
                let magnetics: &Magnetics = ids.downcast_ref().ok_or_else(|| "not a magnetics IDS".to_string())?;
                gather(magnetics, indices, 0, no_levels, |magnetics: &Magnetics, _at: &[usize]| -> FLT_0D {
                    magnetics.latency.clone()
                })
            },
        }),
    },
    Node {
        name: "code",
        documentation: "",
        units: "",
        kind: NodeKind::Structure(NODES_CODE),
    },
];

/// The root of the magnetics data dictionary.
pub static MAGNETICS_ROOT: Node = Node {
    name: "magnetics",
    documentation: "Magnetic diagnostics for equilibrium identification and plasma shape control.",
    units: "",
    kind: NodeKind::Structure(NODES_ROOT),
};
