//! Python bindings for the IMAS data dictionary.
//!
//! # Design
//!
//! The Python surface separates *where* the data lives from *what to read out of it*:
//!
//! ```python
//! from gsfit_rs.imas import equilibrium_paths
//! equilibrium_ids.get(equilibrium_paths.time_slice[:].global_quantities.ip)
//! ```
//!
//! `equilibrium_paths` holds no data at all. It is a cursor over a static description of
//! the data dictionary, so building a path is pure metadata navigation. This is what lets
//! a single [`PyPath`] class serve the whole tree: because there is nothing to borrow,
//! the pyo3 restriction that `#[pyclass]` cannot carry a lifetime never bites.
//!
//! A path is a value. It can be stored in a list, printed, passed around, and reused
//! against several IDSs - which is the point of the `get(path)` form over attribute
//! access that reads immediately.
//!
//! # Where the type hints come from
//!
//! At runtime there is one `Path` class reached through `__getattr__`, and `__dir__`
//! gives tab completion in the REPL. Editors and `mypy` read `python/gsfit_rs/imas.pyi`
//! instead, which declares one class per node and so type-checks every attribute and the
//! return type of `get`. Both the path tables and that stub are emitted by
//! `imas_updater/build_ids.py`; see `equilibrium_paths.rs`.
//!
//! # Layout
//!
//! * `index.rs` - how an array of structures is indexed (`[3]`, `[:]`, `[[0, 2]]`), with
//!   CPython's slice semantics
//! * `description.rs` - the static description types the generated tables are built from
//! * `gather.rs` - the values read back, and gathering a leaf across a sliced array of
//!   structures
//! * `path.rs` - the `Path` cursor, and the reader which resolves one against an IDS
//! * `ids.rs` - the wrapper class for each IDS
//! * `<ids>_paths.rs` - the generated tables, one per IDS; do not edit by hand
//!
//! The generated tables import their building blocks from here (`super::`), which is why
//! everything they need is re-exported below rather than reached through the submodules.

mod description;
mod gather;
mod ids;
mod index;
mod path;

// Generated by `imas_updater/build_ids.py`
mod equilibrium_paths;
mod magnetics_paths;
mod pf_active_paths;
mod pf_passive_paths;
mod tf_paths;
mod wall_paths;

use pyo3::prelude::*;

pub use description::{Leaf, Node, NodeKind};
pub use gather::{Gatherable, LengthOf, Value, gather, no_levels};
pub use ids::{PyEquilibrium, PyMagnetics, PyPfActive, PyPfPassive, PyTf, PyWall};
pub use index::IndexSpec;
pub use path::{PyPath, Segment};

pub use equilibrium_paths::EQUILIBRIUM_ROOT;
pub use magnetics_paths::MAGNETICS_ROOT;
pub use pf_active_paths::PF_ACTIVE_ROOT;
pub use pf_passive_paths::PF_PASSIVE_ROOT;
pub use tf_paths::TF_ROOT;
pub use wall_paths::WALL_ROOT;

/// Populate an `imas` module with the data dictionary bindings.
pub fn register(module: &Bound<'_, PyModule>) -> PyResult<()> {
    module.add_class::<PyPath>()?;
    module.add_class::<PyEquilibrium>()?;
    module.add_class::<PyMagnetics>()?;
    module.add_class::<PyPfActive>()?;
    module.add_class::<PyPfPassive>()?;
    module.add_class::<PyTf>()?;
    module.add_class::<PyWall>()?;
    module.add("equilibrium_paths", PyPath::at_root(&EQUILIBRIUM_ROOT).into_pyobject(module.py())?)?;
    module.add("magnetics_paths", PyPath::at_root(&MAGNETICS_ROOT).into_pyobject(module.py())?)?;
    module.add("pf_active_paths", PyPath::at_root(&PF_ACTIVE_ROOT).into_pyobject(module.py())?)?;
    module.add("pf_passive_paths", PyPath::at_root(&PF_PASSIVE_ROOT).into_pyobject(module.py())?)?;
    module.add("tf_paths", PyPath::at_root(&TF_ROOT).into_pyobject(module.py())?)?;
    module.add("wall_paths", PyPath::at_root(&WALL_ROOT).into_pyobject(module.py())?)?;
    Ok(())
}
