//! IMAS Magnetics IDS
//!
//! **WARNING** This file is autogenerated by `rust/imas_rs/imas_updater/build_ids.py`.
//! Any changes will be overwritten.
//!
//! This module defines the magnetics Interface Data Structure (IDS), generated from the
//! IMAS Data Dictionary XSD schema.

#![allow(dead_code)]
#![allow(non_camel_case_types)]

use crate::dd_base_types::{Accumulator, EMPTY_INT, FLT_0D, FLT_1D, INT_0D, INT_1D, INT_2D, STR_0D, StringAccumulator};

// ============================================================================
// Complex Types
// ============================================================================

/// Rogowski coil
#[derive(Debug, Clone)]
pub struct MagneticsRogowski {
    /// Short string identifier (unique for a given device)
    pub name: STR_0D,
    /// Description, e.g. “channel viewing the upper divertor”
    pub description: STR_0D,
    /// Quantity measured by the sensor
    pub measured_quantity: IdentifierStatic,
    /// List of (R,Z,phi) points defining the position of the coil guiding centre. Values defining a single segment must be entered in contiguous order
    pub position: Vec<Rphiz0dStatic>,
    /// Indices (from the rogowski_coil array of structure) of the partial Rogowskis used to build the coumpound signal (sum of the partial Rogowski signals). Can be set to any unique integer value for each section of a compound Rogowski coil. Use only if ../measure_quantity/index = 5, leave empty otherwise
    pub indices_compound: INT_1D,
    /// Effective area of the loop wrapped around the guiding centre. In case of multiple layers, sum of the areas of each layer
    /// Units: m^2
    pub area: FLT_0D,
    /// Number of turns per unit length. In case of multiple layers, turns are counted for a single layer
    /// Units: m^-1
    pub turns_per_metre: FLT_0D,
    /// Measured current inside the Rogowski coil contour. The normal direction to the Rogowski coil is defined by the order of points in the list of guiding centre positions. The current is positive when oriented in the same direction as the normal.
    /// Units: A
    pub current: SignalFlt1dValidity,
}

impl Default for MagneticsRogowski {
    fn default() -> Self {
        Self {
            name: String::new(),
            description: String::new(),
            measured_quantity: IdentifierStatic::default(),
            position: Vec::new(),
            indices_compound: Default::default(),
            area: f64::NAN,
            turns_per_metre: f64::NAN,
            current: SignalFlt1dValidity::default(),
        }
    }
}

/// Flux loops
#[derive(Debug, Clone)]
pub struct MagneticsFluxLoop {
    /// Short string identifier (unique for a given device)
    pub name: STR_0D,
    /// Description, e.g. “channel viewing the upper divertor”
    pub description: STR_0D,
    /// Flux loop type
    pub r#type: IdentifierStatic,
    /// List of (R,phi,Z) points defining the outline of the flux loop. Leave empty if ../type/index = 6 (differential loop)
    pub position: Vec<Rphiz0dStatic>,
    /// Indices (from the flux_loop array of structures) of the two loops used to build a differential measurement: loop(second index) - loop(first index). Use only if ../type/index = 6, leave empty otherwise.
    pub indices_differential: INT_1D,
    /// Effective area (ratio between flux and average magnetic field over the loop). Leave empty if ../type/index = 6 (differential loop)
    /// Units: m^2
    pub area: FLT_0D,
    /// Integral of 1/R over the loop area (ratio between flux and magnetic rigidity R0.B0). Use only if ../type/index = 3 to 5, leave empty otherwise.
    /// Units: m
    pub gm9: FLT_0D,
    /// Measured magnetic flux through loop with normal to enclosed surface determined by order of points
    /// Units: Wb
    pub flux: SignalFlt1dValidity,
    /// Measured voltage between the loop terminals
    /// Units: V
    pub voltage: SignalFlt1dValidity,
}

impl Default for MagneticsFluxLoop {
    fn default() -> Self {
        Self {
            name: String::new(),
            description: String::new(),
            r#type: IdentifierStatic::default(),
            position: Vec::new(),
            indices_differential: Default::default(),
            area: f64::NAN,
            gm9: f64::NAN,
            flux: SignalFlt1dValidity::default(),
            voltage: SignalFlt1dValidity::default(),
        }
    }
}

/// Non-linear response of the probe
#[derive(Debug, Clone, Default)]
pub struct MagneticsBpolProbeNonLinear {
    /// Array of magnetic field values (corresponding to the assumption of a linear relation between magnetic field and probe coil current), for each of which the probe non-linear response is given in ../b_field_non_linear
    /// Units: T
    pub b_field_linear: FLT_1D,
    /// Magnetic field value taking into account the non-linear response of the probe
    /// Units: T
    pub b_field_non_linear: FLT_1D,
}

/// Poloidal field probes
#[derive(Debug, Clone)]
pub struct MagneticsBpolProbe {
    /// Short string identifier (unique for a given device)
    pub name: STR_0D,
    /// Description, e.g. “channel viewing the upper divertor”
    pub description: STR_0D,
    /// Probe type
    pub r#type: IdentifierStatic,
    /// R, Z, Phi position of the coil centre
    pub position: Rphiz0dStatic,
    /// Angle of the sensor normal vector (vector parallel to the the axis of the coil, n on the diagram) with respect to horizontal plane (clockwise theta-like angle). Zero if sensor normal vector fully in the horizontal plane and oriented towards increasing major radius. Values in [0 , 2Pi]
    /// Units: rad
    pub poloidal_angle: FLT_0D,
    /// Angle of the projection of the sensor normal vector (n) in the horizontal plane with the increasing R direction (i.e. grad(R)) (angle is counter-clockwise from above). Values should be taken modulo pi with values within (-pi/2,pi/2]. Zero if projected sensor normal is parallel to grad(R), pi/2 if it is parallel to grad(phi).
    /// Units: rad
    pub toroidal_angle: FLT_0D,
    /// Indices (from the b_field_pol_probe array of structure) of the two probes used to build the field difference field(second index) - field(first index). Use only if ../type/index = 6, leave empty otherwise
    pub indices_differential: INT_1D,
    /// 3dB bandwith (first index : lower frequency bound, second index : upper frequency bound)
    /// Units: Hz
    pub bandwidth_3db: FLT_1D,
    /// Area of each turn of the sensor; becomes effective area when multiplied by the turns
    /// Units: m^2
    pub area: FLT_0D,
    /// Length of the sensor along it's normal vector (n)
    /// Units: m
    pub length: FLT_0D,
    /// Turns in the coil, including sign
    pub turns: INT_0D,
    /// Magnetic field component in direction of sensor normal axis (n) averaged over sensor volume defined by area and length, where n = cos(poloidal_angle)*cos(toroidal_angle)*grad(R) - sin(poloidal_angle)*grad(Z) + cos(poloidal_angle)*sin(toroidal_angle)*grad(Phi)/norm(grad(Phi))
    /// Units: T
    pub field: SignalFlt1dValidity,
    /// Voltage on the coil terminals
    /// Units: V
    pub voltage: SignalFlt1dValidity,
    /// Non-linear response of the probe (typically in case of a Hall probe)
    pub non_linear_response: MagneticsBpolProbeNonLinear,
}

impl Default for MagneticsBpolProbe {
    fn default() -> Self {
        Self {
            name: String::new(),
            description: String::new(),
            r#type: IdentifierStatic::default(),
            position: Rphiz0dStatic::default(),
            poloidal_angle: f64::NAN,
            toroidal_angle: f64::NAN,
            indices_differential: Default::default(),
            bandwidth_3db: Default::default(),
            area: f64::NAN,
            length: f64::NAN,
            turns: EMPTY_INT,
            field: SignalFlt1dValidity::default(),
            voltage: SignalFlt1dValidity::default(),
            non_linear_response: MagneticsBpolProbeNonLinear::default(),
        }
    }
}

/// Processed quantities derived from the magnetic measurements, using various methods
#[derive(Debug, Clone, Default)]
pub struct MagneticsMethod {
    /// Name of the data processing method
    pub name: STR_0D,
    /// Plasma current. Positive sign means counter-clockwise when viewed from above.
    /// Units: A
    pub ip: SignalFlt1d,
}

/// Processed quantities derived from the magnetic measurements, using various methods
#[derive(Debug, Clone, Default)]
pub struct MagneticsMethodDistinct {
    /// Name of the calculation method
    pub method_name: STR_0D,
    /// Data
    /// Units: as_parent
    pub data: FLT_1D,
    /// Time
    /// Units: s
    pub time: FLT_1D,
}

/// Shunt for current measurement (often located in the divertor structure)
#[derive(Debug, Clone)]
pub struct MagneticsShunt {
    /// Short string identifier (unique for a given device)
    pub name: STR_0D,
    /// Description, e.g. “channel viewing the upper divertor”
    pub description: STR_0D,
    /// Position of shunt terminals
    pub position: LineOfSight2pointsRz,
    /// Shunt resistance
    /// Units: ohm
    pub resistance: FLT_0D,
    /// Voltage on the shunt terminals (Vfirst_point-Vsecond_point)
    /// Units: V
    pub voltage: SignalFlt1dValidity,
    /// If the shunt is located on a given divertor, index of that divertor in the divertors IDS
    pub divertor_index: INT_0D,
    /// If the shunt is located on a divertor target, index of that target in the divertors IDS
    pub target_index: INT_0D,
    /// If the shunt is located on a divertor tile, index of that tile in the divertors IDS
    pub tile_index: INT_0D,
}

impl Default for MagneticsShunt {
    fn default() -> Self {
        Self {
            name: String::new(),
            description: String::new(),
            position: LineOfSight2pointsRz::default(),
            resistance: f64::NAN,
            voltage: SignalFlt1dValidity::default(),
            divertor_index: EMPTY_INT,
            target_index: EMPTY_INT,
            tile_index: EMPTY_INT,
        }
    }
}

/// Standard type for identifiers (static). The three fields: name, index and description are all representations of the same information. Associated with each application of this identifier-type, there should be a translation table defining the three fields for all objects to be identified.
#[derive(Debug, Clone)]
pub struct IdentifierStatic {
    /// Short string identifier
    pub name: STR_0D,
    /// Integer identifier (enumeration index within a list). Private identifier values must be indicated by a negative index.
    pub index: INT_0D,
    /// Verbose description
    pub description: STR_0D,
}

impl Default for IdentifierStatic {
    fn default() -> Self {
        Self {
            name: String::new(),
            index: EMPTY_INT,
            description: String::new(),
        }
    }
}

/// Structure for R, Z, Phi positions (0D, static)
#[derive(Debug, Clone)]
pub struct Rphiz0dStatic {
    /// Major radius
    /// Units: m
    pub r: FLT_0D,
    /// Toroidal angle (oriented counter-clockwise when viewed from above)
    /// Units: rad
    pub phi: FLT_0D,
    /// Height
    /// Units: m
    pub z: FLT_0D,
}

impl Default for Rphiz0dStatic {
    fn default() -> Self {
        Self {
            r: f64::NAN,
            phi: f64::NAN,
            z: f64::NAN,
        }
    }
}

/// Signal (FLT_1D) with its time base and validity flags
#[derive(Debug, Clone)]
pub struct SignalFlt1dValidity {
    /// Data
    /// Units: as_parent
    pub data: FLT_1D,
    /// Indicator of the validity of the data for each time slice. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)
    pub validity_timed: INT_1D,
    /// Indicator of the validity of the data for the whole acquisition period. 0: valid from automated processing, 1: valid and certified by the diagnostic RO; - 1 means problem identified in the data processing (request verification by the diagnostic RO), -2: invalid data, should not be used (values lower than -2 have a code-specific meaning detailing the origin of their invalidity)
    pub validity: INT_0D,
    /// Time
    /// Units: s
    pub time: FLT_1D,
}

impl Default for SignalFlt1dValidity {
    fn default() -> Self {
        Self {
            data: Default::default(),
            validity_timed: Default::default(),
            validity: EMPTY_INT,
            time: Default::default(),
        }
    }
}

/// Signal (FLT_1D) with its time base
#[derive(Debug, Clone, Default)]
pub struct SignalFlt1d {
    /// Data
    /// Units: as_parent
    pub data: FLT_1D,
    /// Time
    /// Units: s
    pub time: FLT_1D,
}

/// Generic description of a line of sight, defined by two points, in R and Z only
#[derive(Debug, Clone, Default)]
pub struct LineOfSight2pointsRz {
    /// Position of the first point
    pub first_point: Rz0dStatic,
    /// Position of the second point
    pub second_point: Rz0dStatic,
}

/// Generic decription of the code-specific parameters for the code that has produced this IDS
#[derive(Debug, Clone, Default)]
pub struct Code {
    /// Name of software generating IDS
    pub name: STR_0D,
    /// Short description of the software (type, purpose)
    pub description: STR_0D,
    /// Unique commit reference of software
    pub commit: STR_0D,
    /// Unique version (tag) of software
    pub version: STR_0D,
    /// URL of software repository
    pub repository: STR_0D,
    /// List of the code specific parameters in XML format
    pub parameters: STR_0D,
    /// Output flag : 0 means the run is successful, other values mean some difficulty has been encountered, the exact meaning is then code specific. Negative values mean the result shall not be used.
    pub output_flag: INT_1D,
    /// List of external libraries used by the code that has produced this IDS
    pub library: Vec<Library>,
}

/// Structure for a single R, Z position (0D, static)
#[derive(Debug, Clone)]
pub struct Rz0dStatic {
    /// Major radius
    /// Units: m
    pub r: FLT_0D,
    /// Height
    /// Units: m
    pub z: FLT_0D,
}

impl Default for Rz0dStatic {
    fn default() -> Self {
        Self { r: f64::NAN, z: f64::NAN }
    }
}

/// Library used by the code that has produced this IDS
#[derive(Debug, Clone, Default)]
pub struct Library {
    /// Name of software
    pub name: STR_0D,
    /// Short description of the software (type, purpose)
    pub description: STR_0D,
    /// Unique commit reference of software
    pub commit: STR_0D,
    /// Unique version (tag) of software
    pub version: STR_0D,
    /// URL of software repository
    pub repository: STR_0D,
    /// List of the code specific parameters in XML format
    pub parameters: STR_0D,
}

// ============================================================================
// Root IDS Structure
// ============================================================================

/// Magnetic diagnostics for equilibrium identification and plasma shape control.
#[derive(Debug, Clone)]
pub struct Magnetics {
    /// Flux loops; partial flux loops can be described. In case of differential loops, the geometry of differential flux loops is stored in the flux_loop indices of the primitive loops. Signals may be stored on the primitive loop indices but this is optional if the index of the primitive loop is referenced by a differential loop index
    pub flux_loop: Vec<MagneticsFluxLoop>,
    /// Poloidal field probes
    pub b_field_pol_probe: Vec<MagneticsBpolProbe>,
    /// Indices of equivalent poloidal field probes (from the b_field_pol_probe array) that differ only by their toroidal position and have the same (R,Z) position and the same coil orientation (poloidal and toroidal angles). Sets of equivalent probes (i.e. sets of (R, Z, poloidal_angle and toroidal_angle) values) are grouped by the first coordinate and the coils belonging to a given set are listed along the second coordinate. As an example, if there are N probes in a poloidal cross section that are replicated at the same poloidal positions and with the same orientation at 8 toroidal positions, the matrix will be of size Nx8.
    pub b_field_pol_probe_equivalent: INT_2D,
    /// Toroidal field probes
    pub b_field_phi_probe: Vec<MagneticsBpolProbe>,
    /// Set of Rogowski coils. If some of the coils form a compound Rogowski sensor, they must be entered in contiguous order
    pub rogowski_coil: Vec<MagneticsRogowski>,
    /// Set of shunt resistances through which currents in the divertor structure are measured. Shunts are modelled as piecewise straight line segments in the poloidal plane.
    pub shunt: Vec<MagneticsShunt>,
    /// Plasma current. Positive sign means counter-clockwise when viewed from above. The array of structure corresponds to a set of calculation methods (starting with the generally recommended method).
    /// Units: A
    pub ip: Vec<MagneticsMethodDistinct>,
    /// Diamagnetic flux. The array of structure corresponds to a set of calculation methods (starting with the generally recommended method). Positive sign means counter-clockwise when viewed from above
    /// Units: Wb
    pub diamagnetic_flux: Vec<MagneticsMethodDistinct>,
    /// Upper bound of the delay between physical information received by the detector and data available on the real-time (RT) network.
    /// Units: s
    pub latency: FLT_0D,
    pub code: Code,
}

impl Default for Magnetics {
    fn default() -> Self {
        Self {
            flux_loop: Vec::new(),
            b_field_pol_probe: Vec::new(),
            b_field_pol_probe_equivalent: Default::default(),
            b_field_phi_probe: Vec::new(),
            rogowski_coil: Vec::new(),
            shunt: Vec::new(),
            ip: Vec::new(),
            diamagnetic_flux: Vec::new(),
            latency: f64::NAN,
            code: Code::default(),
        }
    }
}

// ============================================================================
// View, Accessor, and Accumulator Types
// ============================================================================

// --- Rphiz0dStatic View Types ---

/// View over multiple Rphiz0dStatic with field accumulation
pub struct Rphiz0dStaticSliceView<'a> {
    data: &'a [Rphiz0dStatic],
    pub r: Accumulator<'a, Rphiz0dStatic, FLT_0D>,
    pub phi: Accumulator<'a, Rphiz0dStatic, FLT_0D>,
    pub z: Accumulator<'a, Rphiz0dStatic, FLT_0D>,
}

impl<'a> Rphiz0dStaticSliceView<'a> {
    pub fn new(data: &'a [Rphiz0dStatic]) -> Self {
        Self {
            data,
            r: Accumulator::new(data, |item: &Rphiz0dStatic| item.r),
            phi: Accumulator::new(data, |item: &Rphiz0dStatic| item.phi),
            z: Accumulator::new(data, |item: &Rphiz0dStatic| item.z),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &Rphiz0dStatic> {
        self.data.iter()
    }
}

/// Range-index trait for Rphiz0dStatic - enables the `.field(0..2)` and `.field(..)` slice view
pub trait Rphiz0dStaticIndex<'a> {
    type Output;
    fn get(self, data: &'a [Rphiz0dStatic]) -> Self::Output;
}

impl<'a> Rphiz0dStaticIndex<'a> for std::ops::Range<usize> {
    type Output = Rphiz0dStaticSliceView<'a>;
    fn get(self, data: &'a [Rphiz0dStatic]) -> Self::Output {
        Rphiz0dStaticSliceView::new(&data[self])
    }
}

impl<'a> Rphiz0dStaticIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = Rphiz0dStaticSliceView<'a>;
    fn get(self, data: &'a [Rphiz0dStatic]) -> Self::Output {
        Rphiz0dStaticSliceView::new(&data[self])
    }
}

impl<'a> Rphiz0dStaticIndex<'a> for std::ops::RangeTo<usize> {
    type Output = Rphiz0dStaticSliceView<'a>;
    fn get(self, data: &'a [Rphiz0dStatic]) -> Self::Output {
        Rphiz0dStaticSliceView::new(&data[self])
    }
}

impl<'a> Rphiz0dStaticIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = Rphiz0dStaticSliceView<'a>;
    fn get(self, data: &'a [Rphiz0dStatic]) -> Self::Output {
        Rphiz0dStaticSliceView::new(&data[self])
    }
}

impl<'a> Rphiz0dStaticIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = Rphiz0dStaticSliceView<'a>;
    fn get(self, data: &'a [Rphiz0dStatic]) -> Self::Output {
        Rphiz0dStaticSliceView::new(&data[self])
    }
}

impl<'a> Rphiz0dStaticIndex<'a> for std::ops::RangeFull {
    type Output = Rphiz0dStaticSliceView<'a>;
    fn get(self, data: &'a [Rphiz0dStatic]) -> Self::Output {
        Rphiz0dStaticSliceView::new(data)
    }
}

// --- Library View Types ---

/// View over multiple Library with field accumulation
pub struct LibrarySliceView<'a> {
    data: &'a [Library],
    pub name: StringAccumulator<'a, Library>,
    pub description: StringAccumulator<'a, Library>,
    pub commit: StringAccumulator<'a, Library>,
    pub version: StringAccumulator<'a, Library>,
    pub repository: StringAccumulator<'a, Library>,
    pub parameters: StringAccumulator<'a, Library>,
}

impl<'a> LibrarySliceView<'a> {
    pub fn new(data: &'a [Library]) -> Self {
        Self {
            data,
            name: StringAccumulator::new(data, |item: &Library| item.name.clone()),
            description: StringAccumulator::new(data, |item: &Library| item.description.clone()),
            commit: StringAccumulator::new(data, |item: &Library| item.commit.clone()),
            version: StringAccumulator::new(data, |item: &Library| item.version.clone()),
            repository: StringAccumulator::new(data, |item: &Library| item.repository.clone()),
            parameters: StringAccumulator::new(data, |item: &Library| item.parameters.clone()),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &Library> {
        self.data.iter()
    }
}

/// Range-index trait for Library - enables the `.field(0..2)` and `.field(..)` slice view
pub trait LibraryIndex<'a> {
    type Output;
    fn get(self, data: &'a [Library]) -> Self::Output;
}

impl<'a> LibraryIndex<'a> for std::ops::Range<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeTo<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeFull {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(data)
    }
}

// --- MagneticsFluxLoop View Types ---

/// View over `type` (IdentifierStatic) across multiple MagneticsFluxLoop
pub struct MagneticsFluxLoopTypeView<'a> {
    pub name: StringAccumulator<'a, MagneticsFluxLoop>,
    pub index: Accumulator<'a, MagneticsFluxLoop, INT_0D>,
    pub description: StringAccumulator<'a, MagneticsFluxLoop>,
}

impl<'a> MagneticsFluxLoopTypeView<'a> {
    pub fn new(data: &'a [MagneticsFluxLoop]) -> Self {
        Self {
            name: StringAccumulator::new(data, |item: &MagneticsFluxLoop| item.r#type.name.clone()),
            index: Accumulator::new(data, |item: &MagneticsFluxLoop| item.r#type.index),
            description: StringAccumulator::new(data, |item: &MagneticsFluxLoop| item.r#type.description.clone()),
        }
    }
}

/// View over `flux` (SignalFlt1dValidity) across multiple MagneticsFluxLoop
pub struct MagneticsFluxLoopFluxView<'a> {
    pub validity: Accumulator<'a, MagneticsFluxLoop, INT_0D>,
}

impl<'a> MagneticsFluxLoopFluxView<'a> {
    pub fn new(data: &'a [MagneticsFluxLoop]) -> Self {
        Self {
            validity: Accumulator::new(data, |item: &MagneticsFluxLoop| item.flux.validity),
        }
    }
}

/// View over `voltage` (SignalFlt1dValidity) across multiple MagneticsFluxLoop
pub struct MagneticsFluxLoopVoltageView<'a> {
    pub validity: Accumulator<'a, MagneticsFluxLoop, INT_0D>,
}

impl<'a> MagneticsFluxLoopVoltageView<'a> {
    pub fn new(data: &'a [MagneticsFluxLoop]) -> Self {
        Self {
            validity: Accumulator::new(data, |item: &MagneticsFluxLoop| item.voltage.validity),
        }
    }
}

/// View over multiple MagneticsFluxLoop with field accumulation
pub struct MagneticsFluxLoopSliceView<'a> {
    data: &'a [MagneticsFluxLoop],
    pub name: StringAccumulator<'a, MagneticsFluxLoop>,
    pub description: StringAccumulator<'a, MagneticsFluxLoop>,
    pub r#type: MagneticsFluxLoopTypeView<'a>,
    pub area: Accumulator<'a, MagneticsFluxLoop, FLT_0D>,
    pub gm9: Accumulator<'a, MagneticsFluxLoop, FLT_0D>,
    pub flux: MagneticsFluxLoopFluxView<'a>,
    pub voltage: MagneticsFluxLoopVoltageView<'a>,
}

impl<'a> MagneticsFluxLoopSliceView<'a> {
    pub fn new(data: &'a [MagneticsFluxLoop]) -> Self {
        Self {
            data,
            name: StringAccumulator::new(data, |item: &MagneticsFluxLoop| item.name.clone()),
            description: StringAccumulator::new(data, |item: &MagneticsFluxLoop| item.description.clone()),
            r#type: MagneticsFluxLoopTypeView::new(data),
            area: Accumulator::new(data, |item: &MagneticsFluxLoop| item.area),
            gm9: Accumulator::new(data, |item: &MagneticsFluxLoop| item.gm9),
            flux: MagneticsFluxLoopFluxView::new(data),
            voltage: MagneticsFluxLoopVoltageView::new(data),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &MagneticsFluxLoop> {
        self.data.iter()
    }
}

/// Range-index trait for MagneticsFluxLoop - enables the `.field(0..2)` and `.field(..)` slice view
pub trait MagneticsFluxLoopIndex<'a> {
    type Output;
    fn get(self, data: &'a [MagneticsFluxLoop]) -> Self::Output;
}

impl<'a> MagneticsFluxLoopIndex<'a> for std::ops::Range<usize> {
    type Output = MagneticsFluxLoopSliceView<'a>;
    fn get(self, data: &'a [MagneticsFluxLoop]) -> Self::Output {
        MagneticsFluxLoopSliceView::new(&data[self])
    }
}

impl<'a> MagneticsFluxLoopIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = MagneticsFluxLoopSliceView<'a>;
    fn get(self, data: &'a [MagneticsFluxLoop]) -> Self::Output {
        MagneticsFluxLoopSliceView::new(&data[self])
    }
}

impl<'a> MagneticsFluxLoopIndex<'a> for std::ops::RangeTo<usize> {
    type Output = MagneticsFluxLoopSliceView<'a>;
    fn get(self, data: &'a [MagneticsFluxLoop]) -> Self::Output {
        MagneticsFluxLoopSliceView::new(&data[self])
    }
}

impl<'a> MagneticsFluxLoopIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = MagneticsFluxLoopSliceView<'a>;
    fn get(self, data: &'a [MagneticsFluxLoop]) -> Self::Output {
        MagneticsFluxLoopSliceView::new(&data[self])
    }
}

impl<'a> MagneticsFluxLoopIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = MagneticsFluxLoopSliceView<'a>;
    fn get(self, data: &'a [MagneticsFluxLoop]) -> Self::Output {
        MagneticsFluxLoopSliceView::new(&data[self])
    }
}

impl<'a> MagneticsFluxLoopIndex<'a> for std::ops::RangeFull {
    type Output = MagneticsFluxLoopSliceView<'a>;
    fn get(self, data: &'a [MagneticsFluxLoop]) -> Self::Output {
        MagneticsFluxLoopSliceView::new(data)
    }
}

// --- MagneticsBpolProbe View Types ---

/// View over `type` (IdentifierStatic) across multiple MagneticsBpolProbe
pub struct MagneticsBpolProbeTypeView<'a> {
    pub name: StringAccumulator<'a, MagneticsBpolProbe>,
    pub index: Accumulator<'a, MagneticsBpolProbe, INT_0D>,
    pub description: StringAccumulator<'a, MagneticsBpolProbe>,
}

impl<'a> MagneticsBpolProbeTypeView<'a> {
    pub fn new(data: &'a [MagneticsBpolProbe]) -> Self {
        Self {
            name: StringAccumulator::new(data, |item: &MagneticsBpolProbe| item.r#type.name.clone()),
            index: Accumulator::new(data, |item: &MagneticsBpolProbe| item.r#type.index),
            description: StringAccumulator::new(data, |item: &MagneticsBpolProbe| item.r#type.description.clone()),
        }
    }
}

/// View over `position` (Rphiz0dStatic) across multiple MagneticsBpolProbe
pub struct MagneticsBpolProbePositionView<'a> {
    pub r: Accumulator<'a, MagneticsBpolProbe, FLT_0D>,
    pub phi: Accumulator<'a, MagneticsBpolProbe, FLT_0D>,
    pub z: Accumulator<'a, MagneticsBpolProbe, FLT_0D>,
}

impl<'a> MagneticsBpolProbePositionView<'a> {
    pub fn new(data: &'a [MagneticsBpolProbe]) -> Self {
        Self {
            r: Accumulator::new(data, |item: &MagneticsBpolProbe| item.position.r),
            phi: Accumulator::new(data, |item: &MagneticsBpolProbe| item.position.phi),
            z: Accumulator::new(data, |item: &MagneticsBpolProbe| item.position.z),
        }
    }
}

/// View over `field` (SignalFlt1dValidity) across multiple MagneticsBpolProbe
pub struct MagneticsBpolProbeFieldView<'a> {
    pub validity: Accumulator<'a, MagneticsBpolProbe, INT_0D>,
}

impl<'a> MagneticsBpolProbeFieldView<'a> {
    pub fn new(data: &'a [MagneticsBpolProbe]) -> Self {
        Self {
            validity: Accumulator::new(data, |item: &MagneticsBpolProbe| item.field.validity),
        }
    }
}

/// View over `voltage` (SignalFlt1dValidity) across multiple MagneticsBpolProbe
pub struct MagneticsBpolProbeVoltageView<'a> {
    pub validity: Accumulator<'a, MagneticsBpolProbe, INT_0D>,
}

impl<'a> MagneticsBpolProbeVoltageView<'a> {
    pub fn new(data: &'a [MagneticsBpolProbe]) -> Self {
        Self {
            validity: Accumulator::new(data, |item: &MagneticsBpolProbe| item.voltage.validity),
        }
    }
}

/// View over `non_linear_response` (MagneticsBpolProbeNonLinear) across multiple MagneticsBpolProbe
pub struct MagneticsBpolProbeNonLinearResponseView<'a> {
    _phantom: std::marker::PhantomData<&'a MagneticsBpolProbe>,
}

impl<'a> MagneticsBpolProbeNonLinearResponseView<'a> {
    pub fn new(_data: &'a [MagneticsBpolProbe]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over multiple MagneticsBpolProbe with field accumulation
pub struct MagneticsBpolProbeSliceView<'a> {
    data: &'a [MagneticsBpolProbe],
    pub name: StringAccumulator<'a, MagneticsBpolProbe>,
    pub description: StringAccumulator<'a, MagneticsBpolProbe>,
    pub r#type: MagneticsBpolProbeTypeView<'a>,
    pub position: MagneticsBpolProbePositionView<'a>,
    pub poloidal_angle: Accumulator<'a, MagneticsBpolProbe, FLT_0D>,
    pub toroidal_angle: Accumulator<'a, MagneticsBpolProbe, FLT_0D>,
    pub area: Accumulator<'a, MagneticsBpolProbe, FLT_0D>,
    pub length: Accumulator<'a, MagneticsBpolProbe, FLT_0D>,
    pub turns: Accumulator<'a, MagneticsBpolProbe, INT_0D>,
    pub field: MagneticsBpolProbeFieldView<'a>,
    pub voltage: MagneticsBpolProbeVoltageView<'a>,
    pub non_linear_response: MagneticsBpolProbeNonLinearResponseView<'a>,
}

impl<'a> MagneticsBpolProbeSliceView<'a> {
    pub fn new(data: &'a [MagneticsBpolProbe]) -> Self {
        Self {
            data,
            name: StringAccumulator::new(data, |item: &MagneticsBpolProbe| item.name.clone()),
            description: StringAccumulator::new(data, |item: &MagneticsBpolProbe| item.description.clone()),
            r#type: MagneticsBpolProbeTypeView::new(data),
            position: MagneticsBpolProbePositionView::new(data),
            poloidal_angle: Accumulator::new(data, |item: &MagneticsBpolProbe| item.poloidal_angle),
            toroidal_angle: Accumulator::new(data, |item: &MagneticsBpolProbe| item.toroidal_angle),
            area: Accumulator::new(data, |item: &MagneticsBpolProbe| item.area),
            length: Accumulator::new(data, |item: &MagneticsBpolProbe| item.length),
            turns: Accumulator::new(data, |item: &MagneticsBpolProbe| item.turns),
            field: MagneticsBpolProbeFieldView::new(data),
            voltage: MagneticsBpolProbeVoltageView::new(data),
            non_linear_response: MagneticsBpolProbeNonLinearResponseView::new(data),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &MagneticsBpolProbe> {
        self.data.iter()
    }
}

/// Range-index trait for MagneticsBpolProbe - enables the `.field(0..2)` and `.field(..)` slice view
pub trait MagneticsBpolProbeIndex<'a> {
    type Output;
    fn get(self, data: &'a [MagneticsBpolProbe]) -> Self::Output;
}

impl<'a> MagneticsBpolProbeIndex<'a> for std::ops::Range<usize> {
    type Output = MagneticsBpolProbeSliceView<'a>;
    fn get(self, data: &'a [MagneticsBpolProbe]) -> Self::Output {
        MagneticsBpolProbeSliceView::new(&data[self])
    }
}

impl<'a> MagneticsBpolProbeIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = MagneticsBpolProbeSliceView<'a>;
    fn get(self, data: &'a [MagneticsBpolProbe]) -> Self::Output {
        MagneticsBpolProbeSliceView::new(&data[self])
    }
}

impl<'a> MagneticsBpolProbeIndex<'a> for std::ops::RangeTo<usize> {
    type Output = MagneticsBpolProbeSliceView<'a>;
    fn get(self, data: &'a [MagneticsBpolProbe]) -> Self::Output {
        MagneticsBpolProbeSliceView::new(&data[self])
    }
}

impl<'a> MagneticsBpolProbeIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = MagneticsBpolProbeSliceView<'a>;
    fn get(self, data: &'a [MagneticsBpolProbe]) -> Self::Output {
        MagneticsBpolProbeSliceView::new(&data[self])
    }
}

impl<'a> MagneticsBpolProbeIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = MagneticsBpolProbeSliceView<'a>;
    fn get(self, data: &'a [MagneticsBpolProbe]) -> Self::Output {
        MagneticsBpolProbeSliceView::new(&data[self])
    }
}

impl<'a> MagneticsBpolProbeIndex<'a> for std::ops::RangeFull {
    type Output = MagneticsBpolProbeSliceView<'a>;
    fn get(self, data: &'a [MagneticsBpolProbe]) -> Self::Output {
        MagneticsBpolProbeSliceView::new(data)
    }
}

// --- MagneticsRogowski View Types ---

/// View over `measured_quantity` (IdentifierStatic) across multiple MagneticsRogowski
pub struct MagneticsRogowskiMeasuredQuantityView<'a> {
    pub name: StringAccumulator<'a, MagneticsRogowski>,
    pub index: Accumulator<'a, MagneticsRogowski, INT_0D>,
    pub description: StringAccumulator<'a, MagneticsRogowski>,
}

impl<'a> MagneticsRogowskiMeasuredQuantityView<'a> {
    pub fn new(data: &'a [MagneticsRogowski]) -> Self {
        Self {
            name: StringAccumulator::new(data, |item: &MagneticsRogowski| item.measured_quantity.name.clone()),
            index: Accumulator::new(data, |item: &MagneticsRogowski| item.measured_quantity.index),
            description: StringAccumulator::new(data, |item: &MagneticsRogowski| item.measured_quantity.description.clone()),
        }
    }
}

/// View over `current` (SignalFlt1dValidity) across multiple MagneticsRogowski
pub struct MagneticsRogowskiCurrentView<'a> {
    pub validity: Accumulator<'a, MagneticsRogowski, INT_0D>,
}

impl<'a> MagneticsRogowskiCurrentView<'a> {
    pub fn new(data: &'a [MagneticsRogowski]) -> Self {
        Self {
            validity: Accumulator::new(data, |item: &MagneticsRogowski| item.current.validity),
        }
    }
}

/// View over multiple MagneticsRogowski with field accumulation
pub struct MagneticsRogowskiSliceView<'a> {
    data: &'a [MagneticsRogowski],
    pub name: StringAccumulator<'a, MagneticsRogowski>,
    pub description: StringAccumulator<'a, MagneticsRogowski>,
    pub measured_quantity: MagneticsRogowskiMeasuredQuantityView<'a>,
    pub area: Accumulator<'a, MagneticsRogowski, FLT_0D>,
    pub turns_per_metre: Accumulator<'a, MagneticsRogowski, FLT_0D>,
    pub current: MagneticsRogowskiCurrentView<'a>,
}

impl<'a> MagneticsRogowskiSliceView<'a> {
    pub fn new(data: &'a [MagneticsRogowski]) -> Self {
        Self {
            data,
            name: StringAccumulator::new(data, |item: &MagneticsRogowski| item.name.clone()),
            description: StringAccumulator::new(data, |item: &MagneticsRogowski| item.description.clone()),
            measured_quantity: MagneticsRogowskiMeasuredQuantityView::new(data),
            area: Accumulator::new(data, |item: &MagneticsRogowski| item.area),
            turns_per_metre: Accumulator::new(data, |item: &MagneticsRogowski| item.turns_per_metre),
            current: MagneticsRogowskiCurrentView::new(data),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &MagneticsRogowski> {
        self.data.iter()
    }
}

/// Range-index trait for MagneticsRogowski - enables the `.field(0..2)` and `.field(..)` slice view
pub trait MagneticsRogowskiIndex<'a> {
    type Output;
    fn get(self, data: &'a [MagneticsRogowski]) -> Self::Output;
}

impl<'a> MagneticsRogowskiIndex<'a> for std::ops::Range<usize> {
    type Output = MagneticsRogowskiSliceView<'a>;
    fn get(self, data: &'a [MagneticsRogowski]) -> Self::Output {
        MagneticsRogowskiSliceView::new(&data[self])
    }
}

impl<'a> MagneticsRogowskiIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = MagneticsRogowskiSliceView<'a>;
    fn get(self, data: &'a [MagneticsRogowski]) -> Self::Output {
        MagneticsRogowskiSliceView::new(&data[self])
    }
}

impl<'a> MagneticsRogowskiIndex<'a> for std::ops::RangeTo<usize> {
    type Output = MagneticsRogowskiSliceView<'a>;
    fn get(self, data: &'a [MagneticsRogowski]) -> Self::Output {
        MagneticsRogowskiSliceView::new(&data[self])
    }
}

impl<'a> MagneticsRogowskiIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = MagneticsRogowskiSliceView<'a>;
    fn get(self, data: &'a [MagneticsRogowski]) -> Self::Output {
        MagneticsRogowskiSliceView::new(&data[self])
    }
}

impl<'a> MagneticsRogowskiIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = MagneticsRogowskiSliceView<'a>;
    fn get(self, data: &'a [MagneticsRogowski]) -> Self::Output {
        MagneticsRogowskiSliceView::new(&data[self])
    }
}

impl<'a> MagneticsRogowskiIndex<'a> for std::ops::RangeFull {
    type Output = MagneticsRogowskiSliceView<'a>;
    fn get(self, data: &'a [MagneticsRogowski]) -> Self::Output {
        MagneticsRogowskiSliceView::new(data)
    }
}

// --- MagneticsShunt View Types ---

/// View over `position.first_point` (Rz0dStatic) across multiple MagneticsShunt
pub struct MagneticsShuntPositionFirstPointView<'a> {
    pub r: Accumulator<'a, MagneticsShunt, FLT_0D>,
    pub z: Accumulator<'a, MagneticsShunt, FLT_0D>,
}

impl<'a> MagneticsShuntPositionFirstPointView<'a> {
    pub fn new(data: &'a [MagneticsShunt]) -> Self {
        Self {
            r: Accumulator::new(data, |item: &MagneticsShunt| item.position.first_point.r),
            z: Accumulator::new(data, |item: &MagneticsShunt| item.position.first_point.z),
        }
    }
}

/// View over `position.second_point` (Rz0dStatic) across multiple MagneticsShunt
pub struct MagneticsShuntPositionSecondPointView<'a> {
    pub r: Accumulator<'a, MagneticsShunt, FLT_0D>,
    pub z: Accumulator<'a, MagneticsShunt, FLT_0D>,
}

impl<'a> MagneticsShuntPositionSecondPointView<'a> {
    pub fn new(data: &'a [MagneticsShunt]) -> Self {
        Self {
            r: Accumulator::new(data, |item: &MagneticsShunt| item.position.second_point.r),
            z: Accumulator::new(data, |item: &MagneticsShunt| item.position.second_point.z),
        }
    }
}

/// View over `position` (LineOfSight2pointsRz) across multiple MagneticsShunt
pub struct MagneticsShuntPositionView<'a> {
    pub first_point: MagneticsShuntPositionFirstPointView<'a>,
    pub second_point: MagneticsShuntPositionSecondPointView<'a>,
}

impl<'a> MagneticsShuntPositionView<'a> {
    pub fn new(data: &'a [MagneticsShunt]) -> Self {
        Self {
            first_point: MagneticsShuntPositionFirstPointView::new(data),
            second_point: MagneticsShuntPositionSecondPointView::new(data),
        }
    }
}

/// View over `voltage` (SignalFlt1dValidity) across multiple MagneticsShunt
pub struct MagneticsShuntVoltageView<'a> {
    pub validity: Accumulator<'a, MagneticsShunt, INT_0D>,
}

impl<'a> MagneticsShuntVoltageView<'a> {
    pub fn new(data: &'a [MagneticsShunt]) -> Self {
        Self {
            validity: Accumulator::new(data, |item: &MagneticsShunt| item.voltage.validity),
        }
    }
}

/// View over multiple MagneticsShunt with field accumulation
pub struct MagneticsShuntSliceView<'a> {
    data: &'a [MagneticsShunt],
    pub name: StringAccumulator<'a, MagneticsShunt>,
    pub description: StringAccumulator<'a, MagneticsShunt>,
    pub position: MagneticsShuntPositionView<'a>,
    pub resistance: Accumulator<'a, MagneticsShunt, FLT_0D>,
    pub voltage: MagneticsShuntVoltageView<'a>,
    pub divertor_index: Accumulator<'a, MagneticsShunt, INT_0D>,
    pub target_index: Accumulator<'a, MagneticsShunt, INT_0D>,
    pub tile_index: Accumulator<'a, MagneticsShunt, INT_0D>,
}

impl<'a> MagneticsShuntSliceView<'a> {
    pub fn new(data: &'a [MagneticsShunt]) -> Self {
        Self {
            data,
            name: StringAccumulator::new(data, |item: &MagneticsShunt| item.name.clone()),
            description: StringAccumulator::new(data, |item: &MagneticsShunt| item.description.clone()),
            position: MagneticsShuntPositionView::new(data),
            resistance: Accumulator::new(data, |item: &MagneticsShunt| item.resistance),
            voltage: MagneticsShuntVoltageView::new(data),
            divertor_index: Accumulator::new(data, |item: &MagneticsShunt| item.divertor_index),
            target_index: Accumulator::new(data, |item: &MagneticsShunt| item.target_index),
            tile_index: Accumulator::new(data, |item: &MagneticsShunt| item.tile_index),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &MagneticsShunt> {
        self.data.iter()
    }
}

/// Range-index trait for MagneticsShunt - enables the `.field(0..2)` and `.field(..)` slice view
pub trait MagneticsShuntIndex<'a> {
    type Output;
    fn get(self, data: &'a [MagneticsShunt]) -> Self::Output;
}

impl<'a> MagneticsShuntIndex<'a> for std::ops::Range<usize> {
    type Output = MagneticsShuntSliceView<'a>;
    fn get(self, data: &'a [MagneticsShunt]) -> Self::Output {
        MagneticsShuntSliceView::new(&data[self])
    }
}

impl<'a> MagneticsShuntIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = MagneticsShuntSliceView<'a>;
    fn get(self, data: &'a [MagneticsShunt]) -> Self::Output {
        MagneticsShuntSliceView::new(&data[self])
    }
}

impl<'a> MagneticsShuntIndex<'a> for std::ops::RangeTo<usize> {
    type Output = MagneticsShuntSliceView<'a>;
    fn get(self, data: &'a [MagneticsShunt]) -> Self::Output {
        MagneticsShuntSliceView::new(&data[self])
    }
}

impl<'a> MagneticsShuntIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = MagneticsShuntSliceView<'a>;
    fn get(self, data: &'a [MagneticsShunt]) -> Self::Output {
        MagneticsShuntSliceView::new(&data[self])
    }
}

impl<'a> MagneticsShuntIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = MagneticsShuntSliceView<'a>;
    fn get(self, data: &'a [MagneticsShunt]) -> Self::Output {
        MagneticsShuntSliceView::new(&data[self])
    }
}

impl<'a> MagneticsShuntIndex<'a> for std::ops::RangeFull {
    type Output = MagneticsShuntSliceView<'a>;
    fn get(self, data: &'a [MagneticsShunt]) -> Self::Output {
        MagneticsShuntSliceView::new(data)
    }
}

// --- MagneticsMethodDistinct View Types ---

/// View over multiple MagneticsMethodDistinct with field accumulation
pub struct MagneticsMethodDistinctSliceView<'a> {
    data: &'a [MagneticsMethodDistinct],
    pub method_name: StringAccumulator<'a, MagneticsMethodDistinct>,
}

impl<'a> MagneticsMethodDistinctSliceView<'a> {
    pub fn new(data: &'a [MagneticsMethodDistinct]) -> Self {
        Self {
            data,
            method_name: StringAccumulator::new(data, |item: &MagneticsMethodDistinct| item.method_name.clone()),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &MagneticsMethodDistinct> {
        self.data.iter()
    }
}

/// Range-index trait for MagneticsMethodDistinct - enables the `.field(0..2)` and `.field(..)` slice view
pub trait MagneticsMethodDistinctIndex<'a> {
    type Output;
    fn get(self, data: &'a [MagneticsMethodDistinct]) -> Self::Output;
}

impl<'a> MagneticsMethodDistinctIndex<'a> for std::ops::Range<usize> {
    type Output = MagneticsMethodDistinctSliceView<'a>;
    fn get(self, data: &'a [MagneticsMethodDistinct]) -> Self::Output {
        MagneticsMethodDistinctSliceView::new(&data[self])
    }
}

impl<'a> MagneticsMethodDistinctIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = MagneticsMethodDistinctSliceView<'a>;
    fn get(self, data: &'a [MagneticsMethodDistinct]) -> Self::Output {
        MagneticsMethodDistinctSliceView::new(&data[self])
    }
}

impl<'a> MagneticsMethodDistinctIndex<'a> for std::ops::RangeTo<usize> {
    type Output = MagneticsMethodDistinctSliceView<'a>;
    fn get(self, data: &'a [MagneticsMethodDistinct]) -> Self::Output {
        MagneticsMethodDistinctSliceView::new(&data[self])
    }
}

impl<'a> MagneticsMethodDistinctIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = MagneticsMethodDistinctSliceView<'a>;
    fn get(self, data: &'a [MagneticsMethodDistinct]) -> Self::Output {
        MagneticsMethodDistinctSliceView::new(&data[self])
    }
}

impl<'a> MagneticsMethodDistinctIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = MagneticsMethodDistinctSliceView<'a>;
    fn get(self, data: &'a [MagneticsMethodDistinct]) -> Self::Output {
        MagneticsMethodDistinctSliceView::new(&data[self])
    }
}

impl<'a> MagneticsMethodDistinctIndex<'a> for std::ops::RangeFull {
    type Output = MagneticsMethodDistinctSliceView<'a>;
    fn get(self, data: &'a [MagneticsMethodDistinct]) -> Self::Output {
        MagneticsMethodDistinctSliceView::new(data)
    }
}

// ============================================================================
// Struct Impl Blocks for Vec Field Access
// ============================================================================

impl MagneticsRogowski {
    /// The slice view over a range of position, e.g. `.position(0..2)` or `.position(..)`,
    /// whose leaves gather one value per element. A single element is `.position[i]`.
    pub fn position<'a, I: Rphiz0dStaticIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.position)
    }

    /// Get the number of position elements
    pub fn position_len(&self) -> usize {
        self.position.len()
    }
}

impl MagneticsFluxLoop {
    /// The slice view over a range of position, e.g. `.position(0..2)` or `.position(..)`,
    /// whose leaves gather one value per element. A single element is `.position[i]`.
    pub fn position<'a, I: Rphiz0dStaticIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.position)
    }

    /// Get the number of position elements
    pub fn position_len(&self) -> usize {
        self.position.len()
    }
}

impl Code {
    /// The slice view over a range of library, e.g. `.library(0..2)` or `.library(..)`,
    /// whose leaves gather one value per element. A single element is `.library[i]`.
    pub fn library<'a, I: LibraryIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.library)
    }

    /// Get the number of library elements
    pub fn library_len(&self) -> usize {
        self.library.len()
    }
}

impl Magnetics {
    /// The slice view over a range of flux_loop, e.g. `.flux_loop(0..2)` or `.flux_loop(..)`,
    /// whose leaves gather one value per element. A single element is `.flux_loop[i]`.
    pub fn flux_loop<'a, I: MagneticsFluxLoopIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.flux_loop)
    }

    /// Get the number of flux_loop elements
    pub fn flux_loop_len(&self) -> usize {
        self.flux_loop.len()
    }
}

impl Magnetics {
    /// The slice view over a range of b_field_pol_probe, e.g. `.b_field_pol_probe(0..2)` or `.b_field_pol_probe(..)`,
    /// whose leaves gather one value per element. A single element is `.b_field_pol_probe[i]`.
    pub fn b_field_pol_probe<'a, I: MagneticsBpolProbeIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.b_field_pol_probe)
    }

    /// Get the number of b_field_pol_probe elements
    pub fn b_field_pol_probe_len(&self) -> usize {
        self.b_field_pol_probe.len()
    }
}

impl Magnetics {
    /// The slice view over a range of b_field_phi_probe, e.g. `.b_field_phi_probe(0..2)` or `.b_field_phi_probe(..)`,
    /// whose leaves gather one value per element. A single element is `.b_field_phi_probe[i]`.
    pub fn b_field_phi_probe<'a, I: MagneticsBpolProbeIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.b_field_phi_probe)
    }

    /// Get the number of b_field_phi_probe elements
    pub fn b_field_phi_probe_len(&self) -> usize {
        self.b_field_phi_probe.len()
    }
}

impl Magnetics {
    /// The slice view over a range of rogowski_coil, e.g. `.rogowski_coil(0..2)` or `.rogowski_coil(..)`,
    /// whose leaves gather one value per element. A single element is `.rogowski_coil[i]`.
    pub fn rogowski_coil<'a, I: MagneticsRogowskiIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.rogowski_coil)
    }

    /// Get the number of rogowski_coil elements
    pub fn rogowski_coil_len(&self) -> usize {
        self.rogowski_coil.len()
    }
}

impl Magnetics {
    /// The slice view over a range of shunt, e.g. `.shunt(0..2)` or `.shunt(..)`,
    /// whose leaves gather one value per element. A single element is `.shunt[i]`.
    pub fn shunt<'a, I: MagneticsShuntIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.shunt)
    }

    /// Get the number of shunt elements
    pub fn shunt_len(&self) -> usize {
        self.shunt.len()
    }
}

impl Magnetics {
    /// The slice view over a range of ip, e.g. `.ip(0..2)` or `.ip(..)`,
    /// whose leaves gather one value per element. A single element is `.ip[i]`.
    pub fn ip<'a, I: MagneticsMethodDistinctIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.ip)
    }

    /// Get the number of ip elements
    pub fn ip_len(&self) -> usize {
        self.ip.len()
    }
}

impl Magnetics {
    /// The slice view over a range of diamagnetic_flux, e.g. `.diamagnetic_flux(0..2)` or `.diamagnetic_flux(..)`,
    /// whose leaves gather one value per element. A single element is `.diamagnetic_flux[i]`.
    pub fn diamagnetic_flux<'a, I: MagneticsMethodDistinctIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.diamagnetic_flux)
    }

    /// Get the number of diamagnetic_flux elements
    pub fn diamagnetic_flux_len(&self) -> usize {
        self.diamagnetic_flux.len()
    }
}
