//! IMAS Tf IDS
//!
//! **WARNING** This file is autogenerated by `rust/imas_rs/imas_updater/build_ids.py`.
//! Any changes will be overwritten.
//!
//! This module defines the tf Interface Data Structure (IDS), generated from the
//! IMAS Data Dictionary XSD schema.

#![allow(dead_code)]
#![allow(non_camel_case_types)]

use crate::dd_base_types::{Accumulator, EMPTY_INT, FLT_0D, FLT_1D, FLT_2D, FLT_3D, INT_0D, INT_1D, STR_0D, STR_1D, StringAccumulator};

// ============================================================================
// Complex Types
// ============================================================================

/// Elements descibring the conductor contour
#[derive(Debug, Clone, Default)]
pub struct TfCoilConductorElements {
    /// Name or description of every element
    pub names: STR_1D,
    /// Type of every element: 1: line segment, its ends are given by the start and end points; index = 2: arc of a circle; index = 3: full circle
    pub types: INT_1D,
    /// Position of the start point of every element
    pub start_points: Rphiz1dStatic,
    /// Position of an intermediate point along the arc of circle, for every element, providing the orientation of the element (must define with the corresponding start point an aperture angle strictly inferior to PI). Meaningful only if type/index = 2, fill with default/empty value otherwise
    pub intermediate_points: Rphiz1dStatic,
    /// Position of the end point of every element. Meaningful only if type/index = 1 or 2, fill with default/empty value otherwise
    pub end_points: Rphiz1dStatic,
    /// Position of the centre of the arc of a circle of every element (meaningful only if type/index = 2 or 3, fill with default/empty value otherwise)
    pub centres: Rphiz1dStatic,
}

/// Description of a conductor
#[derive(Debug, Clone)]
pub struct TfCoilConductor {
    /// Set of geometrical elements (line segments and/or arcs of a circle) describing the contour of the TF conductor centre
    pub elements: TfCoilConductorElements,
    /// The cross-section perpendicular to the TF conductor contour is described by a series of contour points, given by their relative position with respect to the start point of the first element. This cross-section is assumed constant for all elements.
    pub cross_section: DeltaRphiz1dStatic,
    /// conductor resistance
    /// Units: ohm
    pub resistance: FLT_0D,
    /// Current in the conductor (positive when it flows from the first to the last element)
    /// Units: A
    pub current: SignalFlt1d,
    /// Voltage on the conductor terminals
    /// Units: V
    pub voltage: SignalFlt1d,
}

impl Default for TfCoilConductor {
    fn default() -> Self {
        Self {
            elements: TfCoilConductorElements::default(),
            cross_section: DeltaRphiz1dStatic::default(),
            resistance: f64::NAN,
            current: SignalFlt1d::default(),
            voltage: SignalFlt1d::default(),
        }
    }
}

/// Description of a given coil
#[derive(Debug, Clone)]
pub struct TfCoil {
    /// Short string identifier (unique for a given device)
    pub name: STR_0D,
    /// Description, e.g. �channel viewing the upper divertor�
    pub description: STR_0D,
    /// Set of conductors inside the coil. The structure can be used with size 1 for a simplified description as a single conductor. A conductor is composed of several elements, serially connected, i.e. transporting the same current.
    pub conductor: Vec<TfCoilConductor>,
    /// Number of total turns in a toroidal field coil. May be a fraction when describing the coil connections.
    pub turns: FLT_0D,
    /// Coil resistance
    /// Units: ohm
    pub resistance: FLT_0D,
    /// Current in the coil
    /// Units: A
    pub current: SignalFlt1d,
    /// Voltage on the coil terminals
    /// Units: V
    pub voltage: SignalFlt1d,
}

impl Default for TfCoil {
    fn default() -> Self {
        Self {
            name: String::new(),
            description: String::new(),
            conductor: Vec::new(),
            turns: f64::NAN,
            resistance: f64::NAN,
            current: SignalFlt1d::default(),
            voltage: SignalFlt1d::default(),
        }
    }
}

/// Toroidal field map represented on ggd
#[derive(Debug, Clone)]
pub struct TfGgd {
    /// Grid description
    pub grid: GenericGridDynamic,
    /// R component of the vacuum magnetic field, given on various grid subsets
    /// Units: T
    pub b_field_r: Vec<GenericGridScalar>,
    /// Z component of the vacuum magnetic field, given on various grid subsets
    /// Units: T
    pub b_field_z: Vec<GenericGridScalar>,
    /// Toroidal component of the vacuum magnetic field, given on various grid subsets
    /// Units: T
    pub b_field_tor: Vec<GenericGridScalar>,
    /// R component of the vacuum vector potential, given on various grid subsets
    /// Units: T.m
    pub a_field_r: Vec<GenericGridScalar>,
    /// Z component of the vacuum vector potential, given on various grid subsets
    /// Units: T.m
    pub a_field_z: Vec<GenericGridScalar>,
    /// Toroidal component of the vacuum vector potential, given on various grid subsets
    /// Units: T.m
    pub a_field_tor: Vec<GenericGridScalar>,
    /// Time
    /// Units: s
    pub time: FLT_0D,
}

impl Default for TfGgd {
    fn default() -> Self {
        Self {
            grid: GenericGridDynamic::default(),
            b_field_r: Vec::new(),
            b_field_z: Vec::new(),
            b_field_tor: Vec::new(),
            a_field_r: Vec::new(),
            a_field_z: Vec::new(),
            a_field_tor: Vec::new(),
            time: f64::NAN,
        }
    }
}

/// Structure for list of R, Z, Phi positions (1D, static)
#[derive(Debug, Clone, Default)]
pub struct Rphiz1dStatic {
    /// Major radius
    /// Units: m
    pub r: FLT_1D,
    /// Toroidal angle (oriented counter-clockwise when viewed from above)
    /// Units: rad
    pub phi: FLT_1D,
    /// Height
    /// Units: m
    pub z: FLT_1D,
}

/// Structure for R, Z, Phi relative positions (1D, static)
#[derive(Debug, Clone, Default)]
pub struct DeltaRphiz1dStatic {
    /// Major radii (relative to a reference point)
    /// Units: m
    pub delta_r: FLT_1D,
    /// Toroidal angles (relative to a reference point)
    /// Units: rad
    pub delta_phi: FLT_1D,
    /// Heights (relative to a reference point)
    /// Units: m
    pub delta_z: FLT_1D,
}

/// Signal (FLT_1D) with its time base
#[derive(Debug, Clone, Default)]
pub struct SignalFlt1d {
    /// Data
    /// Units: as_parent
    pub data: FLT_1D,
    /// Time
    /// Units: s
    pub time: FLT_1D,
}

/// Generic grid (dynamic within a type 3 AoS)
#[derive(Debug, Clone, Default)]
pub struct GenericGridDynamic {
    /// Grid identifier
    pub identifier: IdentifierDynamicAos3,
    /// Path of the grid, including the IDS name, in case of implicit reference to a grid_ggd node described in another IDS. To be filled only if the grid is not described explicitly in this grid_ggd structure. Example syntax: #wall:2/description_ggd(1)/grid_ggd, means that the grid is located in the wall IDS, occurrence 2, with relative path description_ggd(1)/grid_ggd, using Fortran index convention (here : first index of the array)
    pub path: STR_0D,
    /// Set of grid spaces
    pub space: Vec<GenericGridDynamicSpace>,
    /// Grid subsets
    pub grid_subset: Vec<GenericGridDynamicGridSubset>,
}

/// Scalar real values on a generic grid (dynamic within a type 3 AoS)
#[derive(Debug, Clone)]
pub struct GenericGridScalar {
    /// Index of the grid used to represent this quantity
    pub grid_index: INT_0D,
    /// Index of the grid subset the data is provided on. Corresponds to the index used in the grid subset definition: grid_subset(:)/identifier/index
    pub grid_subset_index: INT_0D,
    /// One scalar value is provided per element in the grid subset.
    /// Units: as_parent
    pub values: FLT_1D,
    /// Interpolation coefficients, to be used for a high precision evaluation of the physical quantity with finite elements, provided per element in the grid subset (first dimension).
    /// Units: as_parent
    pub coefficients: FLT_2D,
}

impl Default for GenericGridScalar {
    fn default() -> Self {
        Self {
            grid_index: EMPTY_INT,
            grid_subset_index: EMPTY_INT,
            values: Default::default(),
            coefficients: Default::default(),
        }
    }
}

/// Description of a given coil
#[derive(Debug, Clone)]
pub struct Coil {
    /// Short string identifier (unique for a given device)
    pub name: STR_0D,
    /// Description, e.g. “Coil between sector 1 and 2”
    pub description: STR_0D,
    /// Set of conductors inside the coil. The structure can be used with size 1 for a simplified description as a single conductor. A conductor is composed of several elements, serially connected, i.e. transporting the same current.
    pub conductor: Vec<CoilConductor>,
    /// Number of total turns in the coil. May be a fraction when describing the coil connections.
    pub turns: FLT_0D,
    /// Coil resistance
    /// Units: ohm
    pub resistance: FLT_0D,
    /// Current in one turn of the coil (to be multiplied by the number of turns to calculate the magnetic field generated). Sign convention : a positive current flows in the direction in which conductor elements are ordered (from start to end for a positive polarity coil)
    /// Units: A
    pub current: SignalFlt1d,
    /// Voltage on the coil terminals. Sign convention : positive when the current flows in the direction in which conductor elements are ordered (from start to end for a positive polarity coil)
    /// Units: V
    pub voltage: SignalFlt1d,
    /// Fast neutron flux arriving on the inboard side of this coil
    /// Units: m^-2.s^-1
    pub neutron_fast_flux_inboard: SignalFlt1d,
}

impl Default for Coil {
    fn default() -> Self {
        Self {
            name: String::new(),
            description: String::new(),
            conductor: Vec::new(),
            turns: f64::NAN,
            resistance: f64::NAN,
            current: SignalFlt1d::default(),
            voltage: SignalFlt1d::default(),
            neutron_fast_flux_inboard: SignalFlt1d::default(),
        }
    }
}

/// Generic decription of the code-specific parameters for the code that has produced this IDS
#[derive(Debug, Clone, Default)]
pub struct Code {
    /// Name of software generating IDS
    pub name: STR_0D,
    /// Short description of the software (type, purpose)
    pub description: STR_0D,
    /// Unique commit reference of software
    pub commit: STR_0D,
    /// Unique version (tag) of software
    pub version: STR_0D,
    /// URL of software repository
    pub repository: STR_0D,
    /// List of the code specific parameters in XML format
    pub parameters: STR_0D,
    /// Output flag : 0 means the run is successful, other values mean some difficulty has been encountered, the exact meaning is then code specific. Negative values mean the result shall not be used.
    pub output_flag: INT_1D,
    /// List of external libraries used by the code that has produced this IDS
    pub library: Vec<Library>,
}

/// Standard type for identifiers (dynamic within type 3 array of structures (index on time)). The three fields: name, index and description are all representations of the same information. Associated with each application of this identifier-type, there should be a translation table defining the three fields for all objects to be identified.
#[derive(Debug, Clone)]
pub struct IdentifierDynamicAos3 {
    /// Short string identifier
    pub name: STR_0D,
    /// Integer identifier (enumeration index within a list). Private identifier values must be indicated by a negative index.
    pub index: INT_0D,
    /// Verbose description
    pub description: STR_0D,
}

impl Default for IdentifierDynamicAos3 {
    fn default() -> Self {
        Self {
            name: String::new(),
            index: EMPTY_INT,
            description: String::new(),
        }
    }
}

/// Generic grid space (dynamic within a type 3 AoS)
#[derive(Debug, Clone, Default)]
pub struct GenericGridDynamicSpace {
    /// Space identifier
    pub identifier: IdentifierDynamicAos3,
    /// Type of space geometry (0: standard, 1:Fourier, >1: Fourier with periodicity)
    pub geometry_type: IdentifierDynamicAos3,
    /// Type of coordinates describing the physical space, for every coordinate of the space. The size of this node therefore defines the dimension of the space.
    pub coordinates_type: Vec<IdentifierDynamicAos3>,
    /// Definition of the space objects for every dimension (from one to the dimension of the highest-dimensional objects). The index correspond to 1=nodes, 2=edges, 3=faces, 4=cells/volumes, .... For every index, a collection of objects of that dimension is described.
    pub objects_per_dimension: Vec<GenericGridDynamicSpaceDimension>,
}

/// Generic grid grid_subset (dynamic within a type 3 AoS)
#[derive(Debug, Clone)]
pub struct GenericGridDynamicGridSubset {
    /// Grid subset identifier
    pub identifier: IdentifierDynamicAos3,
    /// Space dimension of the grid subset elements, using the convention 1=nodes, 2=edges, 3=faces, 4=cells/volumes
    pub dimension: INT_0D,
    /// Set of elements defining the grid subset. An element is defined by a combination of objects from potentially all spaces
    pub element: Vec<GenericGridDynamicGridSubsetElement>,
    /// Set of bases for the grid subset. For each base, the structure describes the projection of the base vectors on the canonical frame of the grid.
    pub base: Vec<GenericGridDynamicGridSubsetMetric>,
    /// Metric of the canonical frame onto Cartesian coordinates
    pub metric: GenericGridDynamicGridSubsetMetric,
}

impl Default for GenericGridDynamicGridSubset {
    fn default() -> Self {
        Self {
            identifier: IdentifierDynamicAos3::default(),
            dimension: EMPTY_INT,
            element: Vec::new(),
            base: Vec::new(),
            metric: GenericGridDynamicGridSubsetMetric::default(),
        }
    }
}

/// Description of a conductor
#[derive(Debug, Clone)]
pub struct CoilConductor {
    /// Set of geometrical elements (line segments and/or arcs of a circle) describing the contour of the conductor centre. We define a coordinate system associated to each element as follows: for the arc and circle elements: binormal = (start point - center) x (intermediate point - center). This vector points in the direction of the circle / arc axis. normal = (center - point on curve). The normal vector will rotate as the point moves around the curve. Tangent = normal x binormal. For the line element we require an extra point, using the currently redundant intermediate point to define the line element's normal axis. The local coordinates for the line element then become: tangent = end point - start point; normal = intermediate point - start point; binormal = tangent x normal. It is assumed that all the axes above are normalized such that they have a unit length.
    pub elements: CoilConductorElements,
    /// The cross-section perpendicular to the conductor contour is described by a series of contour points, given by their relative position with respect to the start point of each element. If the size of this array of structure is equal to 1, then the cross-section is given only for the first element and translated along the conductor elements. Otherwise, it's given explictly for each element, allowing to describe changes of the cross section shape
    pub cross_section: Vec<CoilCrossSection>,
    /// conductor resistance
    /// Units: ohm
    pub resistance: FLT_0D,
    /// Voltage on the conductor terminals. Sign convention : positive when the current flows in the direction in which conductor elements are ordered (from start to end for a positive polarity coil)
    /// Units: V
    pub voltage: SignalFlt1d,
}

impl Default for CoilConductor {
    fn default() -> Self {
        Self {
            elements: CoilConductorElements::default(),
            cross_section: Vec::new(),
            resistance: f64::NAN,
            voltage: SignalFlt1d::default(),
        }
    }
}

/// Library used by the code that has produced this IDS
#[derive(Debug, Clone, Default)]
pub struct Library {
    /// Name of software
    pub name: STR_0D,
    /// Short description of the software (type, purpose)
    pub description: STR_0D,
    /// Unique commit reference of software
    pub commit: STR_0D,
    /// Unique version (tag) of software
    pub version: STR_0D,
    /// URL of software repository
    pub repository: STR_0D,
    /// List of the code specific parameters in XML format
    pub parameters: STR_0D,
}

/// Generic grid, list of dimensions within a space (dynamic within a type 3 AoS)
#[derive(Debug, Clone, Default)]
pub struct GenericGridDynamicSpaceDimension {
    /// Set of objects for a given dimension
    pub object: Vec<GenericGridDynamicSpaceDimensionObject>,
    /// Content of the ../object/geometry node for this dimension
    pub geometry_content: IdentifierDynamicAos3,
}

/// Generic grid, element part of a grid_subset (dynamic within a type 3 AoS)
#[derive(Debug, Clone, Default)]
pub struct GenericGridDynamicGridSubsetElement {
    /// Set of objects defining the element
    pub object: Vec<GenericGridDynamicGridSubsetElementObject>,
}

/// Generic grid, metric description for a given grid_subset and base (dynamic within a type 3 AoS)
#[derive(Debug, Clone, Default)]
pub struct GenericGridDynamicGridSubsetMetric {
    /// Metric Jacobian
    /// Units: mixed
    pub jacobian: FLT_1D,
    /// Covariant metric tensor, given on each element of the subgrid (first dimension)
    /// Units: mixed
    pub tensor_covariant: FLT_3D,
    /// Contravariant metric tensor, given on each element of the subgrid (first dimension)
    /// Units: mixed
    pub tensor_contravariant: FLT_3D,
}

/// Elements descibring the conductor contour
#[derive(Debug, Clone, Default)]
pub struct CoilConductorElements {
    /// Type of every element: 1: line segment, its ends are given by the start and end points; index = 2: arc of a circle; index = 3: full circle
    pub types: INT_1D,
    /// Position of the start point of every element
    pub start_points: CoilNaRphiz1dStatic,
    /// Position of an intermediate point along the circle or arc of circle, for every element, providing the orientation of the element (must define with the corresponding start point an aperture angle strictly inferior to PI). In the case of a line segment (../types/index=1), fill this node with a point such that the vector intermediate_point - start_point defines the direction of the element's normal axis (see documentation of ../elements)
    pub intermediate_points: CoilNaRphiz1dStatic,
    /// Position of the end point of every element. Meaningful only if type/index = 1 or 2, fill with default/empty value otherwise
    pub end_points: CoilNaRphiz1dStatic,
    /// Position of the centre of the arc of a circle of every element (meaningful only if type/index = 2 or 3, fill with default/empty value otherwise)
    pub centres: CoilNaRphiz1dStatic,
}

/// Coil cross-section
#[derive(Debug, Clone)]
pub struct CoilCrossSection {
    /// Geometry type used to describe the cross section of this element. The conductor centre is given by the ../../elements description.
    pub geometry_type: IdentifierStatic,
    /// Full width of the rectangle or square in the normal direction, when geometry_type/index = 3 or 4. Diameter of the circle when geometry_type/index = 2. Outer diameter of the annulus in case geometry_type/index = 5
    /// Units: m
    pub width: FLT_0D,
    /// Full height of the rectangle in the binormal direction, used only if geometry_type/index = 3
    /// Units: m
    pub height: FLT_0D,
    /// Inner radius of the annulus, used only if geometry_type/index = 5
    /// Units: m
    pub radius_inner: FLT_0D,
    /// Polygonal outline of the cross section in the (normal, binormal) coordinate system. Do NOT repeat the first point.
    pub outline: NormalBinormalStatic,
    /// Area of the conductor cross-section, derived from the above geometric data
    /// Units: m^2
    pub area: FLT_0D,
}

impl Default for CoilCrossSection {
    fn default() -> Self {
        Self {
            geometry_type: IdentifierStatic::default(),
            width: f64::NAN,
            height: f64::NAN,
            radius_inner: f64::NAN,
            outline: NormalBinormalStatic::default(),
            area: f64::NAN,
        }
    }
}

/// Generic grid, list of objects of a given dimension within a space (dynamic within a type 3 AoS)
#[derive(Debug, Clone)]
pub struct GenericGridDynamicSpaceDimensionObject {
    /// Set of  (n-1)-dimensional objects defining the boundary of this n-dimensional object
    pub boundary: Vec<GenericGridDynamicSpaceDimensionObjectBoundary>,
    /// Geometry data associated with the object, its detailed content is defined by ../../geometry_content. Its dimension depends on the type of object, geometry and coordinate considered.
    /// Units: mixed
    pub geometry: FLT_1D,
    /// List of nodes forming this object (indices to objects_per_dimension(1)%object(:) in Fortran notation)
    pub nodes: INT_1D,
    /// Measure of the space object, i.e. physical size (length for 1d, area for 2d, volume for 3d objects,...)
    /// Units: m^dimension
    pub measure: FLT_0D,
    /// 2D geometry data associated with the object. Its dimension depends on the type of object, geometry and coordinate considered. Typically, the first dimension represents the object coordinates, while the second dimension would represent the values of the various degrees of freedom of the finite element attached to the object.
    /// Units: mixed
    pub geometry_2d: FLT_2D,
}

impl Default for GenericGridDynamicSpaceDimensionObject {
    fn default() -> Self {
        Self {
            boundary: Vec::new(),
            geometry: Default::default(),
            nodes: Default::default(),
            measure: f64::NAN,
            geometry_2d: Default::default(),
        }
    }
}

/// Generic grid, object part of an element part of a grid_subset (dynamic within a type 3 AoS)
#[derive(Debug, Clone)]
pub struct GenericGridDynamicGridSubsetElementObject {
    /// Index of the space from which that object is taken
    pub space: INT_0D,
    /// Dimension of the object - using the convention  1=nodes, 2=edges, 3=faces, 4=cells/volumes
    pub dimension: INT_0D,
    /// Object index
    pub index: INT_0D,
}

impl Default for GenericGridDynamicGridSubsetElementObject {
    fn default() -> Self {
        Self {
            space: EMPTY_INT,
            dimension: EMPTY_INT,
            index: EMPTY_INT,
        }
    }
}

/// Structure for list of R, Z, Phi positions (1D, static), with a reference to the types coordinate specific to this IDS
#[derive(Debug, Clone, Default)]
pub struct CoilNaRphiz1dStatic {
    /// Major radius
    /// Units: m
    pub r: FLT_1D,
    /// Toroidal angle (oriented counter-clockwise when viewed from above)
    /// Units: rad
    pub phi: FLT_1D,
    /// Height
    /// Units: m
    pub z: FLT_1D,
}

/// Standard type for identifiers (static). The three fields: name, index and description are all representations of the same information. Associated with each application of this identifier-type, there should be a translation table defining the three fields for all objects to be identified.
#[derive(Debug, Clone)]
pub struct IdentifierStatic {
    /// Short string identifier
    pub name: STR_0D,
    /// Integer identifier (enumeration index within a list). Private identifier values must be indicated by a negative index.
    pub index: INT_0D,
    /// Verbose description
    pub description: STR_0D,
}

impl Default for IdentifierStatic {
    fn default() -> Self {
        Self {
            name: String::new(),
            index: EMPTY_INT,
            description: String::new(),
        }
    }
}

/// Structure for list of normal, binormal positions (1D, static)
#[derive(Debug, Clone, Default)]
pub struct NormalBinormalStatic {
    /// Coordinate along the normal axis
    /// Units: m
    pub normal: FLT_1D,
    /// Coordinates along the binormal axis
    /// Units: m
    pub binormal: FLT_1D,
}

/// Generic grid, description of an object boundary and its neighbours (dynamic within a type 3 AoS)
#[derive(Debug, Clone)]
pub struct GenericGridDynamicSpaceDimensionObjectBoundary {
    /// Index of this (n-1)-dimensional boundary object
    pub index: INT_0D,
    /// List of indices of the n-dimensional objects adjacent to the given n-dimensional object. An object can possibly have multiple neighbours on a boundary
    pub neighbours: INT_1D,
}

impl Default for GenericGridDynamicSpaceDimensionObjectBoundary {
    fn default() -> Self {
        Self {
            index: EMPTY_INT,
            neighbours: Default::default(),
        }
    }
}

// ============================================================================
// Root IDS Structure
// ============================================================================

/// Toroidal field coils
#[derive(Debug, Clone)]
pub struct Tf {
    /// Reference major radius of the device (from the official description of the device). This node is the placeholder for this official machine description quantity (typically the middle of the vessel at the equatorial midplane, although the exact definition may depend on the device)
    /// Units: m
    pub r0: FLT_0D,
    /// Flag indicating whether coils are described one by one in the coil() structure (flag=0) or whether the coil structure represents only coils having different characteristics (flag = 1, n_coils must be filled in that case). In the latter case, the coil() sequence is repeated periodically around the torus.
    pub is_periodic: INT_0D,
    /// Number of coils around the torus, in case is_periodic = 1
    pub coils_n: INT_0D,
    /// Set of coils around the tokamak
    pub coil: Vec<Coil>,
    /// Map of the vacuum field at various time slices, represented using the generic grid description
    pub field_map: Vec<TfGgd>,
    /// Vacuum magnetic field times major radius within the cage of toroidal field coils. Positive sign means counter-clockwise when viewed from above.
    /// Units: T.m
    pub b_field_phi_vacuum_r: SignalFlt1d,
    /// Variation of (vacuum field times major radius in the toroidal field magnet) from the start of the plasma.
    /// Units: T.m
    pub delta_b_field_phi_vacuum_r: SignalFlt1d,
    /// Upper bound of the delay between input command received from the RT network and actuator starting to react. Applies globally to the system described by this IDS unless specific latencies (e.g. channel-specific or antenna-specific) are provided at a deeper level in the IDS structure.
    /// Units: s
    pub latency: FLT_0D,
    pub code: Code,
}

impl Default for Tf {
    fn default() -> Self {
        Self {
            r0: f64::NAN,
            is_periodic: EMPTY_INT,
            coils_n: EMPTY_INT,
            coil: Vec::new(),
            field_map: Vec::new(),
            b_field_phi_vacuum_r: SignalFlt1d::default(),
            delta_b_field_phi_vacuum_r: SignalFlt1d::default(),
            latency: f64::NAN,
            code: Code::default(),
        }
    }
}

// ============================================================================
// View, Accessor, and Accumulator Types
// ============================================================================

// --- TfCoilConductor View Types ---

/// View over `elements.start_points` (Rphiz1dStatic) across multiple TfCoilConductor
pub struct TfCoilConductorElementsStartPointsView<'a> {
    _phantom: std::marker::PhantomData<&'a TfCoilConductor>,
}

impl<'a> TfCoilConductorElementsStartPointsView<'a> {
    pub fn new(_data: &'a [TfCoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `elements.intermediate_points` (Rphiz1dStatic) across multiple TfCoilConductor
pub struct TfCoilConductorElementsIntermediatePointsView<'a> {
    _phantom: std::marker::PhantomData<&'a TfCoilConductor>,
}

impl<'a> TfCoilConductorElementsIntermediatePointsView<'a> {
    pub fn new(_data: &'a [TfCoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `elements.end_points` (Rphiz1dStatic) across multiple TfCoilConductor
pub struct TfCoilConductorElementsEndPointsView<'a> {
    _phantom: std::marker::PhantomData<&'a TfCoilConductor>,
}

impl<'a> TfCoilConductorElementsEndPointsView<'a> {
    pub fn new(_data: &'a [TfCoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `elements.centres` (Rphiz1dStatic) across multiple TfCoilConductor
pub struct TfCoilConductorElementsCentresView<'a> {
    _phantom: std::marker::PhantomData<&'a TfCoilConductor>,
}

impl<'a> TfCoilConductorElementsCentresView<'a> {
    pub fn new(_data: &'a [TfCoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `elements` (TfCoilConductorElements) across multiple TfCoilConductor
pub struct TfCoilConductorElementsView<'a> {
    pub start_points: TfCoilConductorElementsStartPointsView<'a>,
    pub intermediate_points: TfCoilConductorElementsIntermediatePointsView<'a>,
    pub end_points: TfCoilConductorElementsEndPointsView<'a>,
    pub centres: TfCoilConductorElementsCentresView<'a>,
}

impl<'a> TfCoilConductorElementsView<'a> {
    pub fn new(data: &'a [TfCoilConductor]) -> Self {
        Self {
            start_points: TfCoilConductorElementsStartPointsView::new(data),
            intermediate_points: TfCoilConductorElementsIntermediatePointsView::new(data),
            end_points: TfCoilConductorElementsEndPointsView::new(data),
            centres: TfCoilConductorElementsCentresView::new(data),
        }
    }
}

/// View over `cross_section` (DeltaRphiz1dStatic) across multiple TfCoilConductor
pub struct TfCoilConductorCrossSectionView<'a> {
    _phantom: std::marker::PhantomData<&'a TfCoilConductor>,
}

impl<'a> TfCoilConductorCrossSectionView<'a> {
    pub fn new(_data: &'a [TfCoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `current` (SignalFlt1d) across multiple TfCoilConductor
pub struct TfCoilConductorCurrentView<'a> {
    _phantom: std::marker::PhantomData<&'a TfCoilConductor>,
}

impl<'a> TfCoilConductorCurrentView<'a> {
    pub fn new(_data: &'a [TfCoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `voltage` (SignalFlt1d) across multiple TfCoilConductor
pub struct TfCoilConductorVoltageView<'a> {
    _phantom: std::marker::PhantomData<&'a TfCoilConductor>,
}

impl<'a> TfCoilConductorVoltageView<'a> {
    pub fn new(_data: &'a [TfCoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over multiple TfCoilConductor with field accumulation
pub struct TfCoilConductorSliceView<'a> {
    data: &'a [TfCoilConductor],
    pub elements: TfCoilConductorElementsView<'a>,
    pub cross_section: TfCoilConductorCrossSectionView<'a>,
    pub resistance: Accumulator<'a, TfCoilConductor, FLT_0D>,
    pub current: TfCoilConductorCurrentView<'a>,
    pub voltage: TfCoilConductorVoltageView<'a>,
}

impl<'a> TfCoilConductorSliceView<'a> {
    pub fn new(data: &'a [TfCoilConductor]) -> Self {
        Self {
            data,
            elements: TfCoilConductorElementsView::new(data),
            cross_section: TfCoilConductorCrossSectionView::new(data),
            resistance: Accumulator::new(data, |item: &TfCoilConductor| item.resistance),
            current: TfCoilConductorCurrentView::new(data),
            voltage: TfCoilConductorVoltageView::new(data),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &TfCoilConductor> {
        self.data.iter()
    }
}

/// Range-index trait for TfCoilConductor - enables the `.field(0..2)` and `.field(..)` slice view
pub trait TfCoilConductorIndex<'a> {
    type Output;
    fn get(self, data: &'a [TfCoilConductor]) -> Self::Output;
}

impl<'a> TfCoilConductorIndex<'a> for std::ops::Range<usize> {
    type Output = TfCoilConductorSliceView<'a>;
    fn get(self, data: &'a [TfCoilConductor]) -> Self::Output {
        TfCoilConductorSliceView::new(&data[self])
    }
}

impl<'a> TfCoilConductorIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = TfCoilConductorSliceView<'a>;
    fn get(self, data: &'a [TfCoilConductor]) -> Self::Output {
        TfCoilConductorSliceView::new(&data[self])
    }
}

impl<'a> TfCoilConductorIndex<'a> for std::ops::RangeTo<usize> {
    type Output = TfCoilConductorSliceView<'a>;
    fn get(self, data: &'a [TfCoilConductor]) -> Self::Output {
        TfCoilConductorSliceView::new(&data[self])
    }
}

impl<'a> TfCoilConductorIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = TfCoilConductorSliceView<'a>;
    fn get(self, data: &'a [TfCoilConductor]) -> Self::Output {
        TfCoilConductorSliceView::new(&data[self])
    }
}

impl<'a> TfCoilConductorIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = TfCoilConductorSliceView<'a>;
    fn get(self, data: &'a [TfCoilConductor]) -> Self::Output {
        TfCoilConductorSliceView::new(&data[self])
    }
}

impl<'a> TfCoilConductorIndex<'a> for std::ops::RangeFull {
    type Output = TfCoilConductorSliceView<'a>;
    fn get(self, data: &'a [TfCoilConductor]) -> Self::Output {
        TfCoilConductorSliceView::new(data)
    }
}

// --- GenericGridScalar View Types ---

/// View over multiple GenericGridScalar with field accumulation
pub struct GenericGridScalarSliceView<'a> {
    data: &'a [GenericGridScalar],
    pub grid_index: Accumulator<'a, GenericGridScalar, INT_0D>,
    pub grid_subset_index: Accumulator<'a, GenericGridScalar, INT_0D>,
}

impl<'a> GenericGridScalarSliceView<'a> {
    pub fn new(data: &'a [GenericGridScalar]) -> Self {
        Self {
            data,
            grid_index: Accumulator::new(data, |item: &GenericGridScalar| item.grid_index),
            grid_subset_index: Accumulator::new(data, |item: &GenericGridScalar| item.grid_subset_index),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &GenericGridScalar> {
        self.data.iter()
    }
}

/// Range-index trait for GenericGridScalar - enables the `.field(0..2)` and `.field(..)` slice view
pub trait GenericGridScalarIndex<'a> {
    type Output;
    fn get(self, data: &'a [GenericGridScalar]) -> Self::Output;
}

impl<'a> GenericGridScalarIndex<'a> for std::ops::Range<usize> {
    type Output = GenericGridScalarSliceView<'a>;
    fn get(self, data: &'a [GenericGridScalar]) -> Self::Output {
        GenericGridScalarSliceView::new(&data[self])
    }
}

impl<'a> GenericGridScalarIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = GenericGridScalarSliceView<'a>;
    fn get(self, data: &'a [GenericGridScalar]) -> Self::Output {
        GenericGridScalarSliceView::new(&data[self])
    }
}

impl<'a> GenericGridScalarIndex<'a> for std::ops::RangeTo<usize> {
    type Output = GenericGridScalarSliceView<'a>;
    fn get(self, data: &'a [GenericGridScalar]) -> Self::Output {
        GenericGridScalarSliceView::new(&data[self])
    }
}

impl<'a> GenericGridScalarIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = GenericGridScalarSliceView<'a>;
    fn get(self, data: &'a [GenericGridScalar]) -> Self::Output {
        GenericGridScalarSliceView::new(&data[self])
    }
}

impl<'a> GenericGridScalarIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = GenericGridScalarSliceView<'a>;
    fn get(self, data: &'a [GenericGridScalar]) -> Self::Output {
        GenericGridScalarSliceView::new(&data[self])
    }
}

impl<'a> GenericGridScalarIndex<'a> for std::ops::RangeFull {
    type Output = GenericGridScalarSliceView<'a>;
    fn get(self, data: &'a [GenericGridScalar]) -> Self::Output {
        GenericGridScalarSliceView::new(data)
    }
}

// --- GenericGridDynamicSpace View Types ---

/// View over `identifier` (IdentifierDynamicAos3) across multiple GenericGridDynamicSpace
pub struct GenericGridDynamicSpaceIdentifierView<'a> {
    pub name: StringAccumulator<'a, GenericGridDynamicSpace>,
    pub index: Accumulator<'a, GenericGridDynamicSpace, INT_0D>,
    pub description: StringAccumulator<'a, GenericGridDynamicSpace>,
}

impl<'a> GenericGridDynamicSpaceIdentifierView<'a> {
    pub fn new(data: &'a [GenericGridDynamicSpace]) -> Self {
        Self {
            name: StringAccumulator::new(data, |item: &GenericGridDynamicSpace| item.identifier.name.clone()),
            index: Accumulator::new(data, |item: &GenericGridDynamicSpace| item.identifier.index),
            description: StringAccumulator::new(data, |item: &GenericGridDynamicSpace| item.identifier.description.clone()),
        }
    }
}

/// View over `geometry_type` (IdentifierDynamicAos3) across multiple GenericGridDynamicSpace
pub struct GenericGridDynamicSpaceGeometryTypeView<'a> {
    pub name: StringAccumulator<'a, GenericGridDynamicSpace>,
    pub index: Accumulator<'a, GenericGridDynamicSpace, INT_0D>,
    pub description: StringAccumulator<'a, GenericGridDynamicSpace>,
}

impl<'a> GenericGridDynamicSpaceGeometryTypeView<'a> {
    pub fn new(data: &'a [GenericGridDynamicSpace]) -> Self {
        Self {
            name: StringAccumulator::new(data, |item: &GenericGridDynamicSpace| item.geometry_type.name.clone()),
            index: Accumulator::new(data, |item: &GenericGridDynamicSpace| item.geometry_type.index),
            description: StringAccumulator::new(data, |item: &GenericGridDynamicSpace| item.geometry_type.description.clone()),
        }
    }
}

/// View over multiple GenericGridDynamicSpace with field accumulation
pub struct GenericGridDynamicSpaceSliceView<'a> {
    data: &'a [GenericGridDynamicSpace],
    pub identifier: GenericGridDynamicSpaceIdentifierView<'a>,
    pub geometry_type: GenericGridDynamicSpaceGeometryTypeView<'a>,
}

impl<'a> GenericGridDynamicSpaceSliceView<'a> {
    pub fn new(data: &'a [GenericGridDynamicSpace]) -> Self {
        Self {
            data,
            identifier: GenericGridDynamicSpaceIdentifierView::new(data),
            geometry_type: GenericGridDynamicSpaceGeometryTypeView::new(data),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &GenericGridDynamicSpace> {
        self.data.iter()
    }
}

/// Range-index trait for GenericGridDynamicSpace - enables the `.field(0..2)` and `.field(..)` slice view
pub trait GenericGridDynamicSpaceIndex<'a> {
    type Output;
    fn get(self, data: &'a [GenericGridDynamicSpace]) -> Self::Output;
}

impl<'a> GenericGridDynamicSpaceIndex<'a> for std::ops::Range<usize> {
    type Output = GenericGridDynamicSpaceSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpace]) -> Self::Output {
        GenericGridDynamicSpaceSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = GenericGridDynamicSpaceSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpace]) -> Self::Output {
        GenericGridDynamicSpaceSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceIndex<'a> for std::ops::RangeTo<usize> {
    type Output = GenericGridDynamicSpaceSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpace]) -> Self::Output {
        GenericGridDynamicSpaceSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = GenericGridDynamicSpaceSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpace]) -> Self::Output {
        GenericGridDynamicSpaceSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = GenericGridDynamicSpaceSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpace]) -> Self::Output {
        GenericGridDynamicSpaceSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceIndex<'a> for std::ops::RangeFull {
    type Output = GenericGridDynamicSpaceSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpace]) -> Self::Output {
        GenericGridDynamicSpaceSliceView::new(data)
    }
}

// --- GenericGridDynamicGridSubset View Types ---

/// View over `identifier` (IdentifierDynamicAos3) across multiple GenericGridDynamicGridSubset
pub struct GenericGridDynamicGridSubsetIdentifierView<'a> {
    pub name: StringAccumulator<'a, GenericGridDynamicGridSubset>,
    pub index: Accumulator<'a, GenericGridDynamicGridSubset, INT_0D>,
    pub description: StringAccumulator<'a, GenericGridDynamicGridSubset>,
}

impl<'a> GenericGridDynamicGridSubsetIdentifierView<'a> {
    pub fn new(data: &'a [GenericGridDynamicGridSubset]) -> Self {
        Self {
            name: StringAccumulator::new(data, |item: &GenericGridDynamicGridSubset| item.identifier.name.clone()),
            index: Accumulator::new(data, |item: &GenericGridDynamicGridSubset| item.identifier.index),
            description: StringAccumulator::new(data, |item: &GenericGridDynamicGridSubset| item.identifier.description.clone()),
        }
    }
}

/// View over `metric` (GenericGridDynamicGridSubsetMetric) across multiple GenericGridDynamicGridSubset
pub struct GenericGridDynamicGridSubsetMetricView<'a> {
    _phantom: std::marker::PhantomData<&'a GenericGridDynamicGridSubset>,
}

impl<'a> GenericGridDynamicGridSubsetMetricView<'a> {
    pub fn new(_data: &'a [GenericGridDynamicGridSubset]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over multiple GenericGridDynamicGridSubset with field accumulation
pub struct GenericGridDynamicGridSubsetSliceView<'a> {
    data: &'a [GenericGridDynamicGridSubset],
    pub identifier: GenericGridDynamicGridSubsetIdentifierView<'a>,
    pub dimension: Accumulator<'a, GenericGridDynamicGridSubset, INT_0D>,
    pub metric: GenericGridDynamicGridSubsetMetricView<'a>,
}

impl<'a> GenericGridDynamicGridSubsetSliceView<'a> {
    pub fn new(data: &'a [GenericGridDynamicGridSubset]) -> Self {
        Self {
            data,
            identifier: GenericGridDynamicGridSubsetIdentifierView::new(data),
            dimension: Accumulator::new(data, |item: &GenericGridDynamicGridSubset| item.dimension),
            metric: GenericGridDynamicGridSubsetMetricView::new(data),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &GenericGridDynamicGridSubset> {
        self.data.iter()
    }
}

/// Range-index trait for GenericGridDynamicGridSubset - enables the `.field(0..2)` and `.field(..)` slice view
pub trait GenericGridDynamicGridSubsetIndex<'a> {
    type Output;
    fn get(self, data: &'a [GenericGridDynamicGridSubset]) -> Self::Output;
}

impl<'a> GenericGridDynamicGridSubsetIndex<'a> for std::ops::Range<usize> {
    type Output = GenericGridDynamicGridSubsetSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubset]) -> Self::Output {
        GenericGridDynamicGridSubsetSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = GenericGridDynamicGridSubsetSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubset]) -> Self::Output {
        GenericGridDynamicGridSubsetSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetIndex<'a> for std::ops::RangeTo<usize> {
    type Output = GenericGridDynamicGridSubsetSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubset]) -> Self::Output {
        GenericGridDynamicGridSubsetSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = GenericGridDynamicGridSubsetSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubset]) -> Self::Output {
        GenericGridDynamicGridSubsetSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = GenericGridDynamicGridSubsetSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubset]) -> Self::Output {
        GenericGridDynamicGridSubsetSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetIndex<'a> for std::ops::RangeFull {
    type Output = GenericGridDynamicGridSubsetSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubset]) -> Self::Output {
        GenericGridDynamicGridSubsetSliceView::new(data)
    }
}

// --- CoilConductor View Types ---

/// View over `elements.start_points` (CoilNaRphiz1dStatic) across multiple CoilConductor
pub struct CoilConductorElementsStartPointsView<'a> {
    _phantom: std::marker::PhantomData<&'a CoilConductor>,
}

impl<'a> CoilConductorElementsStartPointsView<'a> {
    pub fn new(_data: &'a [CoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `elements.intermediate_points` (CoilNaRphiz1dStatic) across multiple CoilConductor
pub struct CoilConductorElementsIntermediatePointsView<'a> {
    _phantom: std::marker::PhantomData<&'a CoilConductor>,
}

impl<'a> CoilConductorElementsIntermediatePointsView<'a> {
    pub fn new(_data: &'a [CoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `elements.end_points` (CoilNaRphiz1dStatic) across multiple CoilConductor
pub struct CoilConductorElementsEndPointsView<'a> {
    _phantom: std::marker::PhantomData<&'a CoilConductor>,
}

impl<'a> CoilConductorElementsEndPointsView<'a> {
    pub fn new(_data: &'a [CoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `elements.centres` (CoilNaRphiz1dStatic) across multiple CoilConductor
pub struct CoilConductorElementsCentresView<'a> {
    _phantom: std::marker::PhantomData<&'a CoilConductor>,
}

impl<'a> CoilConductorElementsCentresView<'a> {
    pub fn new(_data: &'a [CoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `elements` (CoilConductorElements) across multiple CoilConductor
pub struct CoilConductorElementsView<'a> {
    pub start_points: CoilConductorElementsStartPointsView<'a>,
    pub intermediate_points: CoilConductorElementsIntermediatePointsView<'a>,
    pub end_points: CoilConductorElementsEndPointsView<'a>,
    pub centres: CoilConductorElementsCentresView<'a>,
}

impl<'a> CoilConductorElementsView<'a> {
    pub fn new(data: &'a [CoilConductor]) -> Self {
        Self {
            start_points: CoilConductorElementsStartPointsView::new(data),
            intermediate_points: CoilConductorElementsIntermediatePointsView::new(data),
            end_points: CoilConductorElementsEndPointsView::new(data),
            centres: CoilConductorElementsCentresView::new(data),
        }
    }
}

/// View over `voltage` (SignalFlt1d) across multiple CoilConductor
pub struct CoilConductorVoltageView<'a> {
    _phantom: std::marker::PhantomData<&'a CoilConductor>,
}

impl<'a> CoilConductorVoltageView<'a> {
    pub fn new(_data: &'a [CoilConductor]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over multiple CoilConductor with field accumulation
pub struct CoilConductorSliceView<'a> {
    data: &'a [CoilConductor],
    pub elements: CoilConductorElementsView<'a>,
    pub resistance: Accumulator<'a, CoilConductor, FLT_0D>,
    pub voltage: CoilConductorVoltageView<'a>,
}

impl<'a> CoilConductorSliceView<'a> {
    pub fn new(data: &'a [CoilConductor]) -> Self {
        Self {
            data,
            elements: CoilConductorElementsView::new(data),
            resistance: Accumulator::new(data, |item: &CoilConductor| item.resistance),
            voltage: CoilConductorVoltageView::new(data),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &CoilConductor> {
        self.data.iter()
    }
}

/// Range-index trait for CoilConductor - enables the `.field(0..2)` and `.field(..)` slice view
pub trait CoilConductorIndex<'a> {
    type Output;
    fn get(self, data: &'a [CoilConductor]) -> Self::Output;
}

impl<'a> CoilConductorIndex<'a> for std::ops::Range<usize> {
    type Output = CoilConductorSliceView<'a>;
    fn get(self, data: &'a [CoilConductor]) -> Self::Output {
        CoilConductorSliceView::new(&data[self])
    }
}

impl<'a> CoilConductorIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = CoilConductorSliceView<'a>;
    fn get(self, data: &'a [CoilConductor]) -> Self::Output {
        CoilConductorSliceView::new(&data[self])
    }
}

impl<'a> CoilConductorIndex<'a> for std::ops::RangeTo<usize> {
    type Output = CoilConductorSliceView<'a>;
    fn get(self, data: &'a [CoilConductor]) -> Self::Output {
        CoilConductorSliceView::new(&data[self])
    }
}

impl<'a> CoilConductorIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = CoilConductorSliceView<'a>;
    fn get(self, data: &'a [CoilConductor]) -> Self::Output {
        CoilConductorSliceView::new(&data[self])
    }
}

impl<'a> CoilConductorIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = CoilConductorSliceView<'a>;
    fn get(self, data: &'a [CoilConductor]) -> Self::Output {
        CoilConductorSliceView::new(&data[self])
    }
}

impl<'a> CoilConductorIndex<'a> for std::ops::RangeFull {
    type Output = CoilConductorSliceView<'a>;
    fn get(self, data: &'a [CoilConductor]) -> Self::Output {
        CoilConductorSliceView::new(data)
    }
}

// --- Library View Types ---

/// View over multiple Library with field accumulation
pub struct LibrarySliceView<'a> {
    data: &'a [Library],
    pub name: StringAccumulator<'a, Library>,
    pub description: StringAccumulator<'a, Library>,
    pub commit: StringAccumulator<'a, Library>,
    pub version: StringAccumulator<'a, Library>,
    pub repository: StringAccumulator<'a, Library>,
    pub parameters: StringAccumulator<'a, Library>,
}

impl<'a> LibrarySliceView<'a> {
    pub fn new(data: &'a [Library]) -> Self {
        Self {
            data,
            name: StringAccumulator::new(data, |item: &Library| item.name.clone()),
            description: StringAccumulator::new(data, |item: &Library| item.description.clone()),
            commit: StringAccumulator::new(data, |item: &Library| item.commit.clone()),
            version: StringAccumulator::new(data, |item: &Library| item.version.clone()),
            repository: StringAccumulator::new(data, |item: &Library| item.repository.clone()),
            parameters: StringAccumulator::new(data, |item: &Library| item.parameters.clone()),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &Library> {
        self.data.iter()
    }
}

/// Range-index trait for Library - enables the `.field(0..2)` and `.field(..)` slice view
pub trait LibraryIndex<'a> {
    type Output;
    fn get(self, data: &'a [Library]) -> Self::Output;
}

impl<'a> LibraryIndex<'a> for std::ops::Range<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeTo<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(&data[self])
    }
}

impl<'a> LibraryIndex<'a> for std::ops::RangeFull {
    type Output = LibrarySliceView<'a>;
    fn get(self, data: &'a [Library]) -> Self::Output {
        LibrarySliceView::new(data)
    }
}

// --- IdentifierDynamicAos3 View Types ---

/// View over multiple IdentifierDynamicAos3 with field accumulation
pub struct IdentifierDynamicAos3SliceView<'a> {
    data: &'a [IdentifierDynamicAos3],
    pub name: StringAccumulator<'a, IdentifierDynamicAos3>,
    pub index: Accumulator<'a, IdentifierDynamicAos3, INT_0D>,
    pub description: StringAccumulator<'a, IdentifierDynamicAos3>,
}

impl<'a> IdentifierDynamicAos3SliceView<'a> {
    pub fn new(data: &'a [IdentifierDynamicAos3]) -> Self {
        Self {
            data,
            name: StringAccumulator::new(data, |item: &IdentifierDynamicAos3| item.name.clone()),
            index: Accumulator::new(data, |item: &IdentifierDynamicAos3| item.index),
            description: StringAccumulator::new(data, |item: &IdentifierDynamicAos3| item.description.clone()),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &IdentifierDynamicAos3> {
        self.data.iter()
    }
}

/// Range-index trait for IdentifierDynamicAos3 - enables the `.field(0..2)` and `.field(..)` slice view
pub trait IdentifierDynamicAos3Index<'a> {
    type Output;
    fn get(self, data: &'a [IdentifierDynamicAos3]) -> Self::Output;
}

impl<'a> IdentifierDynamicAos3Index<'a> for std::ops::Range<usize> {
    type Output = IdentifierDynamicAos3SliceView<'a>;
    fn get(self, data: &'a [IdentifierDynamicAos3]) -> Self::Output {
        IdentifierDynamicAos3SliceView::new(&data[self])
    }
}

impl<'a> IdentifierDynamicAos3Index<'a> for std::ops::RangeFrom<usize> {
    type Output = IdentifierDynamicAos3SliceView<'a>;
    fn get(self, data: &'a [IdentifierDynamicAos3]) -> Self::Output {
        IdentifierDynamicAos3SliceView::new(&data[self])
    }
}

impl<'a> IdentifierDynamicAos3Index<'a> for std::ops::RangeTo<usize> {
    type Output = IdentifierDynamicAos3SliceView<'a>;
    fn get(self, data: &'a [IdentifierDynamicAos3]) -> Self::Output {
        IdentifierDynamicAos3SliceView::new(&data[self])
    }
}

impl<'a> IdentifierDynamicAos3Index<'a> for std::ops::RangeInclusive<usize> {
    type Output = IdentifierDynamicAos3SliceView<'a>;
    fn get(self, data: &'a [IdentifierDynamicAos3]) -> Self::Output {
        IdentifierDynamicAos3SliceView::new(&data[self])
    }
}

impl<'a> IdentifierDynamicAos3Index<'a> for std::ops::RangeToInclusive<usize> {
    type Output = IdentifierDynamicAos3SliceView<'a>;
    fn get(self, data: &'a [IdentifierDynamicAos3]) -> Self::Output {
        IdentifierDynamicAos3SliceView::new(&data[self])
    }
}

impl<'a> IdentifierDynamicAos3Index<'a> for std::ops::RangeFull {
    type Output = IdentifierDynamicAos3SliceView<'a>;
    fn get(self, data: &'a [IdentifierDynamicAos3]) -> Self::Output {
        IdentifierDynamicAos3SliceView::new(data)
    }
}

// --- GenericGridDynamicSpaceDimension View Types ---

/// View over `geometry_content` (IdentifierDynamicAos3) across multiple GenericGridDynamicSpaceDimension
pub struct GenericGridDynamicSpaceDimensionGeometryContentView<'a> {
    pub name: StringAccumulator<'a, GenericGridDynamicSpaceDimension>,
    pub index: Accumulator<'a, GenericGridDynamicSpaceDimension, INT_0D>,
    pub description: StringAccumulator<'a, GenericGridDynamicSpaceDimension>,
}

impl<'a> GenericGridDynamicSpaceDimensionGeometryContentView<'a> {
    pub fn new(data: &'a [GenericGridDynamicSpaceDimension]) -> Self {
        Self {
            name: StringAccumulator::new(data, |item: &GenericGridDynamicSpaceDimension| item.geometry_content.name.clone()),
            index: Accumulator::new(data, |item: &GenericGridDynamicSpaceDimension| item.geometry_content.index),
            description: StringAccumulator::new(data, |item: &GenericGridDynamicSpaceDimension| item.geometry_content.description.clone()),
        }
    }
}

/// View over multiple GenericGridDynamicSpaceDimension with field accumulation
pub struct GenericGridDynamicSpaceDimensionSliceView<'a> {
    data: &'a [GenericGridDynamicSpaceDimension],
    pub geometry_content: GenericGridDynamicSpaceDimensionGeometryContentView<'a>,
}

impl<'a> GenericGridDynamicSpaceDimensionSliceView<'a> {
    pub fn new(data: &'a [GenericGridDynamicSpaceDimension]) -> Self {
        Self {
            data,
            geometry_content: GenericGridDynamicSpaceDimensionGeometryContentView::new(data),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &GenericGridDynamicSpaceDimension> {
        self.data.iter()
    }
}

/// Range-index trait for GenericGridDynamicSpaceDimension - enables the `.field(0..2)` and `.field(..)` slice view
pub trait GenericGridDynamicSpaceDimensionIndex<'a> {
    type Output;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimension]) -> Self::Output;
}

impl<'a> GenericGridDynamicSpaceDimensionIndex<'a> for std::ops::Range<usize> {
    type Output = GenericGridDynamicSpaceDimensionSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimension]) -> Self::Output {
        GenericGridDynamicSpaceDimensionSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = GenericGridDynamicSpaceDimensionSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimension]) -> Self::Output {
        GenericGridDynamicSpaceDimensionSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionIndex<'a> for std::ops::RangeTo<usize> {
    type Output = GenericGridDynamicSpaceDimensionSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimension]) -> Self::Output {
        GenericGridDynamicSpaceDimensionSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = GenericGridDynamicSpaceDimensionSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimension]) -> Self::Output {
        GenericGridDynamicSpaceDimensionSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = GenericGridDynamicSpaceDimensionSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimension]) -> Self::Output {
        GenericGridDynamicSpaceDimensionSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionIndex<'a> for std::ops::RangeFull {
    type Output = GenericGridDynamicSpaceDimensionSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimension]) -> Self::Output {
        GenericGridDynamicSpaceDimensionSliceView::new(data)
    }
}

// --- GenericGridDynamicGridSubsetElement View Types ---

/// View over multiple GenericGridDynamicGridSubsetElement with field accumulation
pub struct GenericGridDynamicGridSubsetElementSliceView<'a> {
    data: &'a [GenericGridDynamicGridSubsetElement],
}

impl<'a> GenericGridDynamicGridSubsetElementSliceView<'a> {
    pub fn new(data: &'a [GenericGridDynamicGridSubsetElement]) -> Self {
        Self { data }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &GenericGridDynamicGridSubsetElement> {
        self.data.iter()
    }
}

/// Range-index trait for GenericGridDynamicGridSubsetElement - enables the `.field(0..2)` and `.field(..)` slice view
pub trait GenericGridDynamicGridSubsetElementIndex<'a> {
    type Output;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElement]) -> Self::Output;
}

impl<'a> GenericGridDynamicGridSubsetElementIndex<'a> for std::ops::Range<usize> {
    type Output = GenericGridDynamicGridSubsetElementSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElement]) -> Self::Output {
        GenericGridDynamicGridSubsetElementSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = GenericGridDynamicGridSubsetElementSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElement]) -> Self::Output {
        GenericGridDynamicGridSubsetElementSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementIndex<'a> for std::ops::RangeTo<usize> {
    type Output = GenericGridDynamicGridSubsetElementSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElement]) -> Self::Output {
        GenericGridDynamicGridSubsetElementSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = GenericGridDynamicGridSubsetElementSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElement]) -> Self::Output {
        GenericGridDynamicGridSubsetElementSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = GenericGridDynamicGridSubsetElementSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElement]) -> Self::Output {
        GenericGridDynamicGridSubsetElementSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementIndex<'a> for std::ops::RangeFull {
    type Output = GenericGridDynamicGridSubsetElementSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElement]) -> Self::Output {
        GenericGridDynamicGridSubsetElementSliceView::new(data)
    }
}

// --- GenericGridDynamicGridSubsetMetric View Types ---

/// View over multiple GenericGridDynamicGridSubsetMetric with field accumulation
pub struct GenericGridDynamicGridSubsetMetricSliceView<'a> {
    data: &'a [GenericGridDynamicGridSubsetMetric],
}

impl<'a> GenericGridDynamicGridSubsetMetricSliceView<'a> {
    pub fn new(data: &'a [GenericGridDynamicGridSubsetMetric]) -> Self {
        Self { data }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &GenericGridDynamicGridSubsetMetric> {
        self.data.iter()
    }
}

/// Range-index trait for GenericGridDynamicGridSubsetMetric - enables the `.field(0..2)` and `.field(..)` slice view
pub trait GenericGridDynamicGridSubsetMetricIndex<'a> {
    type Output;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetMetric]) -> Self::Output;
}

impl<'a> GenericGridDynamicGridSubsetMetricIndex<'a> for std::ops::Range<usize> {
    type Output = GenericGridDynamicGridSubsetMetricSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetMetric]) -> Self::Output {
        GenericGridDynamicGridSubsetMetricSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetMetricIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = GenericGridDynamicGridSubsetMetricSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetMetric]) -> Self::Output {
        GenericGridDynamicGridSubsetMetricSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetMetricIndex<'a> for std::ops::RangeTo<usize> {
    type Output = GenericGridDynamicGridSubsetMetricSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetMetric]) -> Self::Output {
        GenericGridDynamicGridSubsetMetricSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetMetricIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = GenericGridDynamicGridSubsetMetricSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetMetric]) -> Self::Output {
        GenericGridDynamicGridSubsetMetricSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetMetricIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = GenericGridDynamicGridSubsetMetricSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetMetric]) -> Self::Output {
        GenericGridDynamicGridSubsetMetricSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetMetricIndex<'a> for std::ops::RangeFull {
    type Output = GenericGridDynamicGridSubsetMetricSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetMetric]) -> Self::Output {
        GenericGridDynamicGridSubsetMetricSliceView::new(data)
    }
}

// --- CoilCrossSection View Types ---

/// View over `geometry_type` (IdentifierStatic) across multiple CoilCrossSection
pub struct CoilCrossSectionGeometryTypeView<'a> {
    pub name: StringAccumulator<'a, CoilCrossSection>,
    pub index: Accumulator<'a, CoilCrossSection, INT_0D>,
    pub description: StringAccumulator<'a, CoilCrossSection>,
}

impl<'a> CoilCrossSectionGeometryTypeView<'a> {
    pub fn new(data: &'a [CoilCrossSection]) -> Self {
        Self {
            name: StringAccumulator::new(data, |item: &CoilCrossSection| item.geometry_type.name.clone()),
            index: Accumulator::new(data, |item: &CoilCrossSection| item.geometry_type.index),
            description: StringAccumulator::new(data, |item: &CoilCrossSection| item.geometry_type.description.clone()),
        }
    }
}

/// View over `outline` (NormalBinormalStatic) across multiple CoilCrossSection
pub struct CoilCrossSectionOutlineView<'a> {
    _phantom: std::marker::PhantomData<&'a CoilCrossSection>,
}

impl<'a> CoilCrossSectionOutlineView<'a> {
    pub fn new(_data: &'a [CoilCrossSection]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over multiple CoilCrossSection with field accumulation
pub struct CoilCrossSectionSliceView<'a> {
    data: &'a [CoilCrossSection],
    pub geometry_type: CoilCrossSectionGeometryTypeView<'a>,
    pub width: Accumulator<'a, CoilCrossSection, FLT_0D>,
    pub height: Accumulator<'a, CoilCrossSection, FLT_0D>,
    pub radius_inner: Accumulator<'a, CoilCrossSection, FLT_0D>,
    pub outline: CoilCrossSectionOutlineView<'a>,
    pub area: Accumulator<'a, CoilCrossSection, FLT_0D>,
}

impl<'a> CoilCrossSectionSliceView<'a> {
    pub fn new(data: &'a [CoilCrossSection]) -> Self {
        Self {
            data,
            geometry_type: CoilCrossSectionGeometryTypeView::new(data),
            width: Accumulator::new(data, |item: &CoilCrossSection| item.width),
            height: Accumulator::new(data, |item: &CoilCrossSection| item.height),
            radius_inner: Accumulator::new(data, |item: &CoilCrossSection| item.radius_inner),
            outline: CoilCrossSectionOutlineView::new(data),
            area: Accumulator::new(data, |item: &CoilCrossSection| item.area),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &CoilCrossSection> {
        self.data.iter()
    }
}

/// Range-index trait for CoilCrossSection - enables the `.field(0..2)` and `.field(..)` slice view
pub trait CoilCrossSectionIndex<'a> {
    type Output;
    fn get(self, data: &'a [CoilCrossSection]) -> Self::Output;
}

impl<'a> CoilCrossSectionIndex<'a> for std::ops::Range<usize> {
    type Output = CoilCrossSectionSliceView<'a>;
    fn get(self, data: &'a [CoilCrossSection]) -> Self::Output {
        CoilCrossSectionSliceView::new(&data[self])
    }
}

impl<'a> CoilCrossSectionIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = CoilCrossSectionSliceView<'a>;
    fn get(self, data: &'a [CoilCrossSection]) -> Self::Output {
        CoilCrossSectionSliceView::new(&data[self])
    }
}

impl<'a> CoilCrossSectionIndex<'a> for std::ops::RangeTo<usize> {
    type Output = CoilCrossSectionSliceView<'a>;
    fn get(self, data: &'a [CoilCrossSection]) -> Self::Output {
        CoilCrossSectionSliceView::new(&data[self])
    }
}

impl<'a> CoilCrossSectionIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = CoilCrossSectionSliceView<'a>;
    fn get(self, data: &'a [CoilCrossSection]) -> Self::Output {
        CoilCrossSectionSliceView::new(&data[self])
    }
}

impl<'a> CoilCrossSectionIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = CoilCrossSectionSliceView<'a>;
    fn get(self, data: &'a [CoilCrossSection]) -> Self::Output {
        CoilCrossSectionSliceView::new(&data[self])
    }
}

impl<'a> CoilCrossSectionIndex<'a> for std::ops::RangeFull {
    type Output = CoilCrossSectionSliceView<'a>;
    fn get(self, data: &'a [CoilCrossSection]) -> Self::Output {
        CoilCrossSectionSliceView::new(data)
    }
}

// --- GenericGridDynamicSpaceDimensionObject View Types ---

/// View over multiple GenericGridDynamicSpaceDimensionObject with field accumulation
pub struct GenericGridDynamicSpaceDimensionObjectSliceView<'a> {
    data: &'a [GenericGridDynamicSpaceDimensionObject],
    pub measure: Accumulator<'a, GenericGridDynamicSpaceDimensionObject, FLT_0D>,
}

impl<'a> GenericGridDynamicSpaceDimensionObjectSliceView<'a> {
    pub fn new(data: &'a [GenericGridDynamicSpaceDimensionObject]) -> Self {
        Self {
            data,
            measure: Accumulator::new(data, |item: &GenericGridDynamicSpaceDimensionObject| item.measure),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &GenericGridDynamicSpaceDimensionObject> {
        self.data.iter()
    }
}

/// Range-index trait for GenericGridDynamicSpaceDimensionObject - enables the `.field(0..2)` and `.field(..)` slice view
pub trait GenericGridDynamicSpaceDimensionObjectIndex<'a> {
    type Output;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObject]) -> Self::Output;
}

impl<'a> GenericGridDynamicSpaceDimensionObjectIndex<'a> for std::ops::Range<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObject]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObject]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectIndex<'a> for std::ops::RangeTo<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObject]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObject]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObject]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectIndex<'a> for std::ops::RangeFull {
    type Output = GenericGridDynamicSpaceDimensionObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObject]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectSliceView::new(data)
    }
}

// --- GenericGridDynamicGridSubsetElementObject View Types ---

/// View over multiple GenericGridDynamicGridSubsetElementObject with field accumulation
pub struct GenericGridDynamicGridSubsetElementObjectSliceView<'a> {
    data: &'a [GenericGridDynamicGridSubsetElementObject],
    pub space: Accumulator<'a, GenericGridDynamicGridSubsetElementObject, INT_0D>,
    pub dimension: Accumulator<'a, GenericGridDynamicGridSubsetElementObject, INT_0D>,
    pub index: Accumulator<'a, GenericGridDynamicGridSubsetElementObject, INT_0D>,
}

impl<'a> GenericGridDynamicGridSubsetElementObjectSliceView<'a> {
    pub fn new(data: &'a [GenericGridDynamicGridSubsetElementObject]) -> Self {
        Self {
            data,
            space: Accumulator::new(data, |item: &GenericGridDynamicGridSubsetElementObject| item.space),
            dimension: Accumulator::new(data, |item: &GenericGridDynamicGridSubsetElementObject| item.dimension),
            index: Accumulator::new(data, |item: &GenericGridDynamicGridSubsetElementObject| item.index),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &GenericGridDynamicGridSubsetElementObject> {
        self.data.iter()
    }
}

/// Range-index trait for GenericGridDynamicGridSubsetElementObject - enables the `.field(0..2)` and `.field(..)` slice view
pub trait GenericGridDynamicGridSubsetElementObjectIndex<'a> {
    type Output;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElementObject]) -> Self::Output;
}

impl<'a> GenericGridDynamicGridSubsetElementObjectIndex<'a> for std::ops::Range<usize> {
    type Output = GenericGridDynamicGridSubsetElementObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElementObject]) -> Self::Output {
        GenericGridDynamicGridSubsetElementObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementObjectIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = GenericGridDynamicGridSubsetElementObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElementObject]) -> Self::Output {
        GenericGridDynamicGridSubsetElementObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementObjectIndex<'a> for std::ops::RangeTo<usize> {
    type Output = GenericGridDynamicGridSubsetElementObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElementObject]) -> Self::Output {
        GenericGridDynamicGridSubsetElementObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementObjectIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = GenericGridDynamicGridSubsetElementObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElementObject]) -> Self::Output {
        GenericGridDynamicGridSubsetElementObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementObjectIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = GenericGridDynamicGridSubsetElementObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElementObject]) -> Self::Output {
        GenericGridDynamicGridSubsetElementObjectSliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicGridSubsetElementObjectIndex<'a> for std::ops::RangeFull {
    type Output = GenericGridDynamicGridSubsetElementObjectSliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicGridSubsetElementObject]) -> Self::Output {
        GenericGridDynamicGridSubsetElementObjectSliceView::new(data)
    }
}

// --- GenericGridDynamicSpaceDimensionObjectBoundary View Types ---

/// View over multiple GenericGridDynamicSpaceDimensionObjectBoundary with field accumulation
pub struct GenericGridDynamicSpaceDimensionObjectBoundarySliceView<'a> {
    data: &'a [GenericGridDynamicSpaceDimensionObjectBoundary],
    pub index: Accumulator<'a, GenericGridDynamicSpaceDimensionObjectBoundary, INT_0D>,
}

impl<'a> GenericGridDynamicSpaceDimensionObjectBoundarySliceView<'a> {
    pub fn new(data: &'a [GenericGridDynamicSpaceDimensionObjectBoundary]) -> Self {
        Self {
            data,
            index: Accumulator::new(data, |item: &GenericGridDynamicSpaceDimensionObjectBoundary| item.index),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &GenericGridDynamicSpaceDimensionObjectBoundary> {
        self.data.iter()
    }
}

/// Range-index trait for GenericGridDynamicSpaceDimensionObjectBoundary - enables the `.field(0..2)` and `.field(..)` slice view
pub trait GenericGridDynamicSpaceDimensionObjectBoundaryIndex<'a> {
    type Output;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObjectBoundary]) -> Self::Output;
}

impl<'a> GenericGridDynamicSpaceDimensionObjectBoundaryIndex<'a> for std::ops::Range<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectBoundarySliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObjectBoundary]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectBoundarySliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectBoundaryIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectBoundarySliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObjectBoundary]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectBoundarySliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectBoundaryIndex<'a> for std::ops::RangeTo<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectBoundarySliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObjectBoundary]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectBoundarySliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectBoundaryIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectBoundarySliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObjectBoundary]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectBoundarySliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectBoundaryIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = GenericGridDynamicSpaceDimensionObjectBoundarySliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObjectBoundary]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectBoundarySliceView::new(&data[self])
    }
}

impl<'a> GenericGridDynamicSpaceDimensionObjectBoundaryIndex<'a> for std::ops::RangeFull {
    type Output = GenericGridDynamicSpaceDimensionObjectBoundarySliceView<'a>;
    fn get(self, data: &'a [GenericGridDynamicSpaceDimensionObjectBoundary]) -> Self::Output {
        GenericGridDynamicSpaceDimensionObjectBoundarySliceView::new(data)
    }
}

// --- Coil View Types ---

/// View over `current` (SignalFlt1d) across multiple Coil
pub struct CoilCurrentView<'a> {
    _phantom: std::marker::PhantomData<&'a Coil>,
}

impl<'a> CoilCurrentView<'a> {
    pub fn new(_data: &'a [Coil]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `voltage` (SignalFlt1d) across multiple Coil
pub struct CoilVoltageView<'a> {
    _phantom: std::marker::PhantomData<&'a Coil>,
}

impl<'a> CoilVoltageView<'a> {
    pub fn new(_data: &'a [Coil]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over `neutron_fast_flux_inboard` (SignalFlt1d) across multiple Coil
pub struct CoilNeutronFastFluxInboardView<'a> {
    _phantom: std::marker::PhantomData<&'a Coil>,
}

impl<'a> CoilNeutronFastFluxInboardView<'a> {
    pub fn new(_data: &'a [Coil]) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

/// View over multiple Coil with field accumulation
pub struct CoilSliceView<'a> {
    data: &'a [Coil],
    pub name: StringAccumulator<'a, Coil>,
    pub description: StringAccumulator<'a, Coil>,
    pub turns: Accumulator<'a, Coil, FLT_0D>,
    pub resistance: Accumulator<'a, Coil, FLT_0D>,
    pub current: CoilCurrentView<'a>,
    pub voltage: CoilVoltageView<'a>,
    pub neutron_fast_flux_inboard: CoilNeutronFastFluxInboardView<'a>,
}

impl<'a> CoilSliceView<'a> {
    pub fn new(data: &'a [Coil]) -> Self {
        Self {
            data,
            name: StringAccumulator::new(data, |item: &Coil| item.name.clone()),
            description: StringAccumulator::new(data, |item: &Coil| item.description.clone()),
            turns: Accumulator::new(data, |item: &Coil| item.turns),
            resistance: Accumulator::new(data, |item: &Coil| item.resistance),
            current: CoilCurrentView::new(data),
            voltage: CoilVoltageView::new(data),
            neutron_fast_flux_inboard: CoilNeutronFastFluxInboardView::new(data),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &Coil> {
        self.data.iter()
    }
}

/// Range-index trait for Coil - enables the `.field(0..2)` and `.field(..)` slice view
pub trait CoilIndex<'a> {
    type Output;
    fn get(self, data: &'a [Coil]) -> Self::Output;
}

impl<'a> CoilIndex<'a> for std::ops::Range<usize> {
    type Output = CoilSliceView<'a>;
    fn get(self, data: &'a [Coil]) -> Self::Output {
        CoilSliceView::new(&data[self])
    }
}

impl<'a> CoilIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = CoilSliceView<'a>;
    fn get(self, data: &'a [Coil]) -> Self::Output {
        CoilSliceView::new(&data[self])
    }
}

impl<'a> CoilIndex<'a> for std::ops::RangeTo<usize> {
    type Output = CoilSliceView<'a>;
    fn get(self, data: &'a [Coil]) -> Self::Output {
        CoilSliceView::new(&data[self])
    }
}

impl<'a> CoilIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = CoilSliceView<'a>;
    fn get(self, data: &'a [Coil]) -> Self::Output {
        CoilSliceView::new(&data[self])
    }
}

impl<'a> CoilIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = CoilSliceView<'a>;
    fn get(self, data: &'a [Coil]) -> Self::Output {
        CoilSliceView::new(&data[self])
    }
}

impl<'a> CoilIndex<'a> for std::ops::RangeFull {
    type Output = CoilSliceView<'a>;
    fn get(self, data: &'a [Coil]) -> Self::Output {
        CoilSliceView::new(data)
    }
}

// --- TfGgd View Types ---

/// View over `grid.identifier` (IdentifierDynamicAos3) across multiple TfGgd
pub struct TfGgdGridIdentifierView<'a> {
    pub name: StringAccumulator<'a, TfGgd>,
    pub index: Accumulator<'a, TfGgd, INT_0D>,
    pub description: StringAccumulator<'a, TfGgd>,
}

impl<'a> TfGgdGridIdentifierView<'a> {
    pub fn new(data: &'a [TfGgd]) -> Self {
        Self {
            name: StringAccumulator::new(data, |item: &TfGgd| item.grid.identifier.name.clone()),
            index: Accumulator::new(data, |item: &TfGgd| item.grid.identifier.index),
            description: StringAccumulator::new(data, |item: &TfGgd| item.grid.identifier.description.clone()),
        }
    }
}

/// View over `grid` (GenericGridDynamic) across multiple TfGgd
pub struct TfGgdGridView<'a> {
    pub identifier: TfGgdGridIdentifierView<'a>,
    pub path: StringAccumulator<'a, TfGgd>,
}

impl<'a> TfGgdGridView<'a> {
    pub fn new(data: &'a [TfGgd]) -> Self {
        Self {
            identifier: TfGgdGridIdentifierView::new(data),
            path: StringAccumulator::new(data, |item: &TfGgd| item.grid.path.clone()),
        }
    }
}

/// View over multiple TfGgd with field accumulation
pub struct TfGgdSliceView<'a> {
    data: &'a [TfGgd],
    pub grid: TfGgdGridView<'a>,
    pub time: Accumulator<'a, TfGgd, FLT_0D>,
}

impl<'a> TfGgdSliceView<'a> {
    pub fn new(data: &'a [TfGgd]) -> Self {
        Self {
            data,
            grid: TfGgdGridView::new(data),
            time: Accumulator::new(data, |item: &TfGgd| item.time),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }

    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }

    pub fn iter(&self) -> impl Iterator<Item = &TfGgd> {
        self.data.iter()
    }
}

/// Range-index trait for TfGgd - enables the `.field(0..2)` and `.field(..)` slice view
pub trait TfGgdIndex<'a> {
    type Output;
    fn get(self, data: &'a [TfGgd]) -> Self::Output;
}

impl<'a> TfGgdIndex<'a> for std::ops::Range<usize> {
    type Output = TfGgdSliceView<'a>;
    fn get(self, data: &'a [TfGgd]) -> Self::Output {
        TfGgdSliceView::new(&data[self])
    }
}

impl<'a> TfGgdIndex<'a> for std::ops::RangeFrom<usize> {
    type Output = TfGgdSliceView<'a>;
    fn get(self, data: &'a [TfGgd]) -> Self::Output {
        TfGgdSliceView::new(&data[self])
    }
}

impl<'a> TfGgdIndex<'a> for std::ops::RangeTo<usize> {
    type Output = TfGgdSliceView<'a>;
    fn get(self, data: &'a [TfGgd]) -> Self::Output {
        TfGgdSliceView::new(&data[self])
    }
}

impl<'a> TfGgdIndex<'a> for std::ops::RangeInclusive<usize> {
    type Output = TfGgdSliceView<'a>;
    fn get(self, data: &'a [TfGgd]) -> Self::Output {
        TfGgdSliceView::new(&data[self])
    }
}

impl<'a> TfGgdIndex<'a> for std::ops::RangeToInclusive<usize> {
    type Output = TfGgdSliceView<'a>;
    fn get(self, data: &'a [TfGgd]) -> Self::Output {
        TfGgdSliceView::new(&data[self])
    }
}

impl<'a> TfGgdIndex<'a> for std::ops::RangeFull {
    type Output = TfGgdSliceView<'a>;
    fn get(self, data: &'a [TfGgd]) -> Self::Output {
        TfGgdSliceView::new(data)
    }
}

// ============================================================================
// Struct Impl Blocks for Vec Field Access
// ============================================================================

impl TfCoil {
    /// The slice view over a range of conductor, e.g. `.conductor(0..2)` or `.conductor(..)`,
    /// whose leaves gather one value per element. A single element is `.conductor[i]`.
    pub fn conductor<'a, I: TfCoilConductorIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.conductor)
    }

    /// Get the number of conductor elements
    pub fn conductor_len(&self) -> usize {
        self.conductor.len()
    }
}

impl TfGgd {
    /// The slice view over a range of b_field_r, e.g. `.b_field_r(0..2)` or `.b_field_r(..)`,
    /// whose leaves gather one value per element. A single element is `.b_field_r[i]`.
    pub fn b_field_r<'a, I: GenericGridScalarIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.b_field_r)
    }

    /// Get the number of b_field_r elements
    pub fn b_field_r_len(&self) -> usize {
        self.b_field_r.len()
    }
}

impl TfGgd {
    /// The slice view over a range of b_field_z, e.g. `.b_field_z(0..2)` or `.b_field_z(..)`,
    /// whose leaves gather one value per element. A single element is `.b_field_z[i]`.
    pub fn b_field_z<'a, I: GenericGridScalarIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.b_field_z)
    }

    /// Get the number of b_field_z elements
    pub fn b_field_z_len(&self) -> usize {
        self.b_field_z.len()
    }
}

impl TfGgd {
    /// The slice view over a range of b_field_tor, e.g. `.b_field_tor(0..2)` or `.b_field_tor(..)`,
    /// whose leaves gather one value per element. A single element is `.b_field_tor[i]`.
    pub fn b_field_tor<'a, I: GenericGridScalarIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.b_field_tor)
    }

    /// Get the number of b_field_tor elements
    pub fn b_field_tor_len(&self) -> usize {
        self.b_field_tor.len()
    }
}

impl TfGgd {
    /// The slice view over a range of a_field_r, e.g. `.a_field_r(0..2)` or `.a_field_r(..)`,
    /// whose leaves gather one value per element. A single element is `.a_field_r[i]`.
    pub fn a_field_r<'a, I: GenericGridScalarIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.a_field_r)
    }

    /// Get the number of a_field_r elements
    pub fn a_field_r_len(&self) -> usize {
        self.a_field_r.len()
    }
}

impl TfGgd {
    /// The slice view over a range of a_field_z, e.g. `.a_field_z(0..2)` or `.a_field_z(..)`,
    /// whose leaves gather one value per element. A single element is `.a_field_z[i]`.
    pub fn a_field_z<'a, I: GenericGridScalarIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.a_field_z)
    }

    /// Get the number of a_field_z elements
    pub fn a_field_z_len(&self) -> usize {
        self.a_field_z.len()
    }
}

impl TfGgd {
    /// The slice view over a range of a_field_tor, e.g. `.a_field_tor(0..2)` or `.a_field_tor(..)`,
    /// whose leaves gather one value per element. A single element is `.a_field_tor[i]`.
    pub fn a_field_tor<'a, I: GenericGridScalarIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.a_field_tor)
    }

    /// Get the number of a_field_tor elements
    pub fn a_field_tor_len(&self) -> usize {
        self.a_field_tor.len()
    }
}

impl GenericGridDynamic {
    /// The slice view over a range of space, e.g. `.space(0..2)` or `.space(..)`,
    /// whose leaves gather one value per element. A single element is `.space[i]`.
    pub fn space<'a, I: GenericGridDynamicSpaceIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.space)
    }

    /// Get the number of space elements
    pub fn space_len(&self) -> usize {
        self.space.len()
    }
}

impl GenericGridDynamic {
    /// The slice view over a range of grid_subset, e.g. `.grid_subset(0..2)` or `.grid_subset(..)`,
    /// whose leaves gather one value per element. A single element is `.grid_subset[i]`.
    pub fn grid_subset<'a, I: GenericGridDynamicGridSubsetIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.grid_subset)
    }

    /// Get the number of grid_subset elements
    pub fn grid_subset_len(&self) -> usize {
        self.grid_subset.len()
    }
}

impl Coil {
    /// The slice view over a range of conductor, e.g. `.conductor(0..2)` or `.conductor(..)`,
    /// whose leaves gather one value per element. A single element is `.conductor[i]`.
    pub fn conductor<'a, I: CoilConductorIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.conductor)
    }

    /// Get the number of conductor elements
    pub fn conductor_len(&self) -> usize {
        self.conductor.len()
    }
}

impl Code {
    /// The slice view over a range of library, e.g. `.library(0..2)` or `.library(..)`,
    /// whose leaves gather one value per element. A single element is `.library[i]`.
    pub fn library<'a, I: LibraryIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.library)
    }

    /// Get the number of library elements
    pub fn library_len(&self) -> usize {
        self.library.len()
    }
}

impl GenericGridDynamicSpace {
    /// The slice view over a range of coordinates_type, e.g. `.coordinates_type(0..2)` or `.coordinates_type(..)`,
    /// whose leaves gather one value per element. A single element is `.coordinates_type[i]`.
    pub fn coordinates_type<'a, I: IdentifierDynamicAos3Index<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.coordinates_type)
    }

    /// Get the number of coordinates_type elements
    pub fn coordinates_type_len(&self) -> usize {
        self.coordinates_type.len()
    }
}

impl GenericGridDynamicSpace {
    /// The slice view over a range of objects_per_dimension, e.g. `.objects_per_dimension(0..2)` or `.objects_per_dimension(..)`,
    /// whose leaves gather one value per element. A single element is `.objects_per_dimension[i]`.
    pub fn objects_per_dimension<'a, I: GenericGridDynamicSpaceDimensionIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.objects_per_dimension)
    }

    /// Get the number of objects_per_dimension elements
    pub fn objects_per_dimension_len(&self) -> usize {
        self.objects_per_dimension.len()
    }
}

impl GenericGridDynamicGridSubset {
    /// The slice view over a range of element, e.g. `.element(0..2)` or `.element(..)`,
    /// whose leaves gather one value per element. A single element is `.element[i]`.
    pub fn element<'a, I: GenericGridDynamicGridSubsetElementIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.element)
    }

    /// Get the number of element elements
    pub fn element_len(&self) -> usize {
        self.element.len()
    }
}

impl GenericGridDynamicGridSubset {
    /// The slice view over a range of base, e.g. `.base(0..2)` or `.base(..)`,
    /// whose leaves gather one value per element. A single element is `.base[i]`.
    pub fn base<'a, I: GenericGridDynamicGridSubsetMetricIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.base)
    }

    /// Get the number of base elements
    pub fn base_len(&self) -> usize {
        self.base.len()
    }
}

impl CoilConductor {
    /// The slice view over a range of cross_section, e.g. `.cross_section(0..2)` or `.cross_section(..)`,
    /// whose leaves gather one value per element. A single element is `.cross_section[i]`.
    pub fn cross_section<'a, I: CoilCrossSectionIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.cross_section)
    }

    /// Get the number of cross_section elements
    pub fn cross_section_len(&self) -> usize {
        self.cross_section.len()
    }
}

impl GenericGridDynamicSpaceDimension {
    /// The slice view over a range of object, e.g. `.object(0..2)` or `.object(..)`,
    /// whose leaves gather one value per element. A single element is `.object[i]`.
    pub fn object<'a, I: GenericGridDynamicSpaceDimensionObjectIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.object)
    }

    /// Get the number of object elements
    pub fn object_len(&self) -> usize {
        self.object.len()
    }
}

impl GenericGridDynamicGridSubsetElement {
    /// The slice view over a range of object, e.g. `.object(0..2)` or `.object(..)`,
    /// whose leaves gather one value per element. A single element is `.object[i]`.
    pub fn object<'a, I: GenericGridDynamicGridSubsetElementObjectIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.object)
    }

    /// Get the number of object elements
    pub fn object_len(&self) -> usize {
        self.object.len()
    }
}

impl GenericGridDynamicSpaceDimensionObject {
    /// The slice view over a range of boundary, e.g. `.boundary(0..2)` or `.boundary(..)`,
    /// whose leaves gather one value per element. A single element is `.boundary[i]`.
    pub fn boundary<'a, I: GenericGridDynamicSpaceDimensionObjectBoundaryIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.boundary)
    }

    /// Get the number of boundary elements
    pub fn boundary_len(&self) -> usize {
        self.boundary.len()
    }
}

impl Tf {
    /// The slice view over a range of coil, e.g. `.coil(0..2)` or `.coil(..)`,
    /// whose leaves gather one value per element. A single element is `.coil[i]`.
    pub fn coil<'a, I: CoilIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.coil)
    }

    /// Get the number of coil elements
    pub fn coil_len(&self) -> usize {
        self.coil.len()
    }
}

impl Tf {
    /// The slice view over a range of field_map, e.g. `.field_map(0..2)` or `.field_map(..)`,
    /// whose leaves gather one value per element. A single element is `.field_map[i]`.
    pub fn field_map<'a, I: TfGgdIndex<'a>>(&'a self, index: I) -> I::Output {
        index.get(&self.field_map)
    }

    /// Get the number of field_map elements
    pub fn field_map_len(&self) -> usize {
        self.field_map.len()
    }
}
